### ISSUE TITLE
Bug: Styles of sbb-error missing of no sbb-form-field loades

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1125]
**Describe the bug**
When no sbb-form-field is/was displayed - the sbb-error is not styled correctly in standalone mode: Typo + color is wrong.
Note: this does _not_ happen if on a previous view the form field was shown!

**To Reproduce**
1. create a view that contains sbb-error but no sbb-form-field

**Expected behavior**
sbb-error should always be styled correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/117919/153839978-3f7967bd-1a16-4b91-a0c6-c6c7703769dd.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 13.5.0

**Comment by jeripeierSBB** [comment]
This happens because sbb-error styles are only shipped with sbb-form-field component. We will check this issue.
