### ISSUE TITLE
Bug: Visual Focus Helper has problems with Overlay after scrolling

### ISSUE THREAD

**Issue by jonasch** [sbb-design-systems/sbb-angular#1155]
**Describe the bug**
The lightbox overlay from ESTA (using Angular Material) messes around with the scroll coordinates on the page.
This leads to a behaviour, where the flying focus cannot calculate the correct position, when you have a scroll offset and then open a lightbox container. The offset, that the flying focus ring element has to the focussed element, is the exact offset from the scrolling on the main page before.

**To Reproduce**
1. Go to ['Stackblitz'](https://stackblitz.com/edit/angular-batxms?file=src%2Fapp%2Flightbox-component-example.html)
2. Tab until you are on the upper button. Press Enter/Space and tab through Lightbox - all fine
3. Scroll/Tab down until you see the lower button, click it and tab through the open lightbox. 
4. See that the ring element of the 'flying focus' is positioned above the correct element by the scroll distance

**Expected behavior**
I expect, that opening the lightbox overlay does not have any impact on the scrollY and scrollX attributes of window or other containers.

**Screenshots**

1. Lightbox Tab Before scroll:
![image](https://user-images.githubusercontent.com/9671803/154496543-8dc5ff42-eb5b-4d0d-9170-238c9fb4d028.png)

2. Scrolling on Y axis 
![image](https://user-images.githubusercontent.com/9671803/154496336-450245f7-c64d-4795-aeab-1be0053d92e7.png)

3. Lightbox Tab after scroll:
![image](https://user-images.githubusercontent.com/9671803/154496156-974484dc-3634-48fb-b394-6a186e404a24.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge, Chrome

**Additional context**
I tried to debug the flying focus to find if the calculation of the position can be improved on that library side. Within the lightbox overlay the scrollY (and probably scrollX) property on window are resetted to 0, even though, they were > 0 after scrolling outside the lightbox.
Maybe the positionStrategy from angular material get things weird in here. I would have expect to get any scroll information on any element in the document, but there were nothing to find for me. Maybe you can have another approach with config on side of the cdk overlay.

**Comment by jeripeierSBB** [comment]
Hallo @jonasch , did you already receive an answer from the sbbch team regarding the flying focus implementation?

**Comment by mhaertwig** [comment]
@jonasch is this still an issue? If not, we're going to close this.
