### ISSUE TITLE
Bug: autocomplete list not displayed on small screens

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#116]
**Describe the bug**
Dropdown-Menu of autocomplete list is only displayed for a short time on small screens

**To Reproduce**
1. Go to https://sbb-angular.app.sbb.ch/latest/public/components/autocomplete
2. Resize window to a small size
3. Click in input area
4. dropdown menu is displayed for a short time and then is being hidden

**Expected behavior**
Dropdown-Menu should be displayed even if it doesn't fit on the screen (for example scrolling, or display less entries)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by kyubisation** [comment]
![video-20190724-064204-7b7f69c7](https://user-images.githubusercontent.com/594745/61778218-a0a55900-adfe-11e9-8ac6-4ddb0609f492.gif)

**Comment by jeripeierSBB** [comment]
Also On <sbb-dropdown> it's not possible to scroll. So if there are a lot of entries, the user can't see all possibilities.

**Comment by jeripeierSBB** [comment]
![image](https://user-images.githubusercontent.com/29278232/61781765-3d6af500-ae05-11e9-8a5d-a7c2295c58cd.png)

**Comment by kyubisation** [comment]
This is partially by design. The amount of shown entries can very easily be controlled by you.
But I'll certainly have a look at the disappearing autocomplete.

**Comment by gianluca-r** [comment]
Issue appears in Chrome but not Firefox.
It only happens when the autocomplete list is supposed to open above the input field and seems to related to the cdk-overlay's position. I could make it work in Chrome by adding _offsetY: -120_ to the "overlay above input" PositionStrategy (autocomplete-trigger.directive.ts:668):
```
private _getOverlayPosition(): PositionStrategy {
    this._positionStrategy = this._overlay
      .position()
      .flexibleConnectedTo(this._getConnectedElement())
      .withFlexibleDimensions(false)
      .withPush(false)
      .withPositions([
        {
          originX: 'start',
          originY: 'bottom',
          overlayX: 'start',
          overlayY: 'top'
        },
        {
          originX: 'start',
          originY: 'top',
          overlayX: 'start',
          overlayY: 'bottom',
          offsetY: -120
        }
      ]);

    return this._positionStrategy;
  }
```
Relevant issue: https://github.com/angular/components/issues/15481
