### ISSUE TITLE
Bug: Font size in user menu seems to be wrong

### ISSUE THREAD

**Issue by ReToCode** [sbb-design-systems/sbb-angular#118]
Details see https://issues.sbb.ch/browse/TMS-12738.

**Comment by kyubisation** [comment]
Please provide more details. 
There is a bug report template. Please use that if possible.

- What version are you using?
- When does this happen?
- Can you provide a reproduction?

**Comment by kyubisation** [comment]
@ReToCode I need more information to proceed.

**Comment by jeripeierSBB** [comment]
Already fixed
