### ISSUE TITLE
Bug: Logo in IconAppIconComponent off center

### ISSUE THREAD

**Issue by germannp** [sbb-design-systems/sbb-angular#119]
The SBB logo in the [IconAppIconComponent](https://angular.app.sbb.ch/latest/content/IconAppIconComponent)-Icon is vertically off center. Disturbs me, but might be a feature ;-)

PS: The Logo in the GitHub account avatar is also off center, but in the other direction ...

**Comment by kyubisation** [comment]
Maybe @mcilurzo knows what that is the case?

**Comment by mcilurzo** [comment]
I have adjusted the icon and sent it to @kyubisation
