### ISSUE TITLE
Feature Request: Radiobutton(panel) not working with value objects

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1250]
**Describe the bug**
sbb-radio-button(-panel) is not working with object (i.e. non-primitive) values.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-vu5yfr?file=src/app/radio-button-panel-simple-example.html
2. Observe that even though the form value is equal to a value of radio-button-panel, it is _not_ selected

**Expected behavior**
sbb-radio-group should provide some `trackBy` functionality to allow consumers to provide custom equality checks.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: SACL 13.8.0

**Comment by kyubisation** [comment]
What real world use case are you trying to solve here?
This is also more a feature request, since the current functionality works as intended.

**Comment by daniel-sc** [comment]
Hi @kyubisation 

our need comes from the product selection:
![image](https://user-images.githubusercontent.com/117919/156776997-6f30cbe2-001b-4af1-ae8a-a6d730474a3c.png)
The "product" is modeled as an object (id, description, ..) in both, the master data (that creates the listed options) and the order (that contains the current selection).

Of course one could as well argue it is a bug, as the radio button components have no documented restriction on primitive values - but the issue type is not of interest for me ;)

**Comment by kyubisation** [comment]
We discussed this internally in depth and have decided to reject this. We feel that this deviates too much from the native experience and can be achieved fairly easily with a map to track keys and objects.
I apologize for not providing more help.
