### ISSUE TITLE
Bug: Autocomplete opened events inconsistent

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1274]
**Describe the bug**
The "closed" event of the autocomplete event is missing if - after filtering - there are no options displayed when the focus is lost.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-84fpps?file=src/app/autocomplete-reactive-forms-example.html
2. Click enter "asdf" in the input
3. Click somewhere to leave the input field (blur)
4. Observe that no "closed" event is emitted

**Expected behavior**
The "closed" event should be emitted when the user moves away from the input (not when there are no options).

**Screenshots**
![autocomplete-close-event](https://user-images.githubusercontent.com/117919/157657732-a6c113ed-716b-4e62-bf6d-27b908202865.gif)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: chrome
 - Version: SACL 13.8.0

**Additional context**
We need to implement a lazy computation of the options to optimize performance. For this we need consistent opened/closed events to know when we need to compute the current list of options.

**Comment by daniel-sc** [comment]
@mhaertwig , @jeripeierSBB from what I read in #1320 the fix is not exactly as expected - see description:

> Expected behavior
The "closed" event should be emitted when the user moves away from the input (not when there are no options).

Do I understand correctly that the new/changed behavior is to emit the closed event when there are no more options (but focus is still on the component)? Would it be possible to support the expected behavior?

**Comment by jeripeierSBB** [comment]
@jeripeierSBB in my opinion this should fix both cases. Did you already test?

**Comment by mhaertwig** [comment]
@daniel-sc the `opened` and `closed` events refer to the panel and are emitted when the panel opens or closes. So, yes, the `closed` event is emitted if the focus is still on the component.

If that's not what you need can you maybe use `closed` and `blur` together?

**Comment by daniel-sc** [comment]
do you have a pre-release/snapshot published, that I can use for testing?

**Comment by jeripeierSBB** [comment]
We have only our staging url: https://staging-sbb-angular.app.sbb.ch/master/, but you can't create a stackblitz example from that. We will probably create a release on thursday.

**Comment by daniel-sc** [comment]
@mhaertwig this should be possible - I'll try it when using the next release
