### ISSUE TITLE
Feature request: Checkbox-Panel: Allow content below flexbox

### ISSUE THREAD

**Issue by schneidermayer** [sbb-design-systems/sbb-angular#1380]
**Is your feature request related to a problem? Please describe.**
I want to insert full width content below the flexbox. Currently, any content inserted below will also be part of the flexbox:

![image](https://user-images.githubusercontent.com/5674044/162398828-857a747f-342e-468f-b0c0-d53b61336aa9.png)

I can wrap it in some extra `<div>`s to dirty fix it, but it breaks the rest:

![image](https://user-images.githubusercontent.com/5674044/162398428-835dd1cd-ccf2-4476-8bce-e05333bfa44c.png)

The `<hr>` and the "Wunschsitzplatz wählen" link are the content I want to insert.

**Describe the solution you'd like**
A new attribute, something like `sbb-checkbox-panel-subtitle` that inserts content below the flexbox. So this new feature would be opt-in / downward-compatible.

**Describe alternatives you've considered**
Wrapping it in multiple div's and overwriting the css. Tedious and dirty. While it could be fixed easily in the lib.

**EDIT:**
Also the link is not clickable with my workaround. There is no way to make this work properly outside the lib.
Please consider this fix soon, having a link together with a checkbox is something pretty common on websites (basically, any "✅ Accept the [Terms and Conditions]"). We now have the oppurtinity to place the link outside the label, which is better according to Mozilla Spec. So we could solve this better than 95 % of the websites having such combination.

Any help would be highly appreciated.

**Comment by kyubisation** [comment]
@schneidermayer What kind of content would you like to display? Also, would the expecation be that a click on this content should toggle the checkbox or be inert?

**Comment by schneidermayer** [comment]
Edit: Currently clicking the link does not trigger the checkbox, so it already works perfectly in this regard.

**Comment by kyubisation** [comment]
From an accessibility perspective, placing an interactive element (like button or link) inside a label is strongly discouraged: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#interactive_content
However, we could place the content outside of the label, but inside the panel. Since this slightly changes the functionality/expectation of the panel, we need to check this with UX in our refinement tomorrow.

**Comment by schneidermayer** [comment]
> From an accessibility perspective, placing an interactive element (like button or link) inside a label is strongly discouraged
Makes sense, didn't think about that.

> However, we could place the content outside of the label, but inside the panel. Since this slightly changes the functionality/expectation of the panel, we need to check this with UX in our refinement tomorrow.

Alright, thanks for the quick reply.

**Comment by mhaertwig** [comment]
We apologize for the delay. We did extensive accessibility investigations and realized that this could not be implemented in a WCAG-compliant way (especially the radio-button case for which the current implementation of SBB.ch fails the specification).

Unfortunately we therefore have to close this issue as we cannot achieve this pattern.
