### ISSUE TITLE
Bug: Radio Button circle shrinks on small screens

### ISSUE THREAD

**Issue by bollerdominik** [sbb-design-systems/sbb-angular#141]
**Describe the bug**
Radio Button circle shrinks on small screens

**To Reproduce**
Use a sbb-radio-button in a small screen or within a small container.
See:
https://stackblitz.com/edit/angular-sbb-l954ew

**Expected behavior**
Radio button circle keeps the same size on all screen sizes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, Edge, IE, Chrome

**Comment by efux** [comment]
This also happens with checkboxes. See https://stackblitz.com/edit/angular-sbb-rzg7ws
