### ISSUE TITLE
Bug: sbb-select doesn't show a red border when its formControl is invalid

### ISSUE THREAD

**Issue by uzysset** [sbb-design-systems/sbb-angular#145]
**Describe the bug**
<sbb-select> doesn't display a red border if its related formControl is invalid!

**Expected behavior**
<sbb-select> should display a red border if its related formControl is invalid!

**Additional context**
Any other form-component eg. <sbb-autocomplete> that wraps an <input> field has this behaviour..

**Comment by kyubisation** [comment]
Our naive expectation was, that a select would never be invalid, since you can control, what is shown.
We will fix this.
