### ISSUE TITLE
Bug: Missing characters in French Font

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#1564]
**Describe the bug**
Some characters (not sure if this is the right term) are missing int the french fonts.

**To Reproduce**
1. Open any project with any sbb-angular version
2. Add a heading/paragraph/whatever eg `<h1>nœuds</h1>` to one of the components
3. See that the œ portion of the text will use the fallback font

**Expected behavior**
I'd like the font to support these special characters.

**Screenshots**
![Screenshot 2022-07-04 at 10 05 28](https://user-images.githubusercontent.com/25688064/177110457-4ea2ce38-f011-4f8c-b07d-635afa7ae31e.png)
(I adjusted the font variable to make the issue more clear for the screenshot. It's like this: `--sbb-font-light: SBBWeb Light, Serif;`)

**Desktop & Smartphone:**
any

Thanks for your work!

**Comment by kyubisation** [comment]
Thank you for the feedback.
From what I know, there is no way to change the font. @mcilurzo Is this correct?

**Comment by sandrooco** [comment]
@kyubisation & @mcilurzo, have there been any developments regarding this issue?
As far as I know there are versions of the font that include such characters, maybe they could be added to the sbb angular version too?

**Comment by kyubisation** [comment]
We use the "official"/same version as sbb.ch does. I'm not aware that there is another font. We can maybe ask the corresponding contact, if you have additional details?

**Comment by sandrooco** [comment]
Hi @kyubisation after a long journey of mails and calls I found out that the "missing" character is available in the full font but not the subset version (which is used in SBB Angular and exists for quicker load times).

Full: https://cdn.app.sbb.ch/fonts/**v1**/SBBWeb-Light.woff2
Subset: https://cdn.app.sbb.ch/fonts/**v1_6_subset**/SBBWeb-Light.woff2

I propose that developers using SBB Angular can somehow configure which versions they want, maybe even only for certain types (example: we currently only need the œ in the Light font). With this possibility developers could use the subset for best performance and situationally the full font.

Is this something you consider feasable?

**Comment by kyubisation** [comment]
Thank you for the investigation. 👍 
Feasible, yes, although a bit tricky. CSS has no useful option of loading fonts conditionally for this use case. We could probably override the subset font, but that way we would always load both font variants, which is not desirable.
I'm going to experiment with CSS variables and check, if that might be a possible solution.

**Comment by kyubisation** [comment]
Bad news; It does not work with CSS variables. We will discuss our options internally and get back to you.

**Comment by sandrooco** [comment]
Thanks a lot @mhaertwig & @kyubisation - we really appreciate it!
