### ISSUE TITLE
Bug: Hover Tooltip prevents click on trigger element to propagate

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1568]
**Describe the bug**
Before, when using the tooltip with trigger=hover clicks were propagated to parent elements.
This is neccessary for us, as we include hover tooltips in table cells and have a click-handler on the row level.

**To Reproduce**
1. generate a tooltip with trigger=hover inside a wrapper that has a click handler
2. click on the tooltip trigger
3. observe that the click handler is _not_ invoced

**Expected behavior**
Click handler should be invoked.

**Additional context**
Maybe related to https://github.com/sbb-design-systems/sbb-angular/commit/f84c82a1e293e3099b4e9ff3029d14e840ffc1b8

**Comment by kyubisation** [comment]
We disabled the click propagation due to an undesired behavior when using the tooltip in a sbb-form-field label with a sbb-select. I'm not convinced that letting the event bubble even on hover is the right approach, but we'll probably still revert the behavior for hover to support you.
