### ISSUE TITLE
Bug: Lean Notification type "warn" with wrong color

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1569]
**Describe the bug**
With v13 and in https://digital.sbb.ch/de/webapps/components/notification the warn notification has an orange color:
![image](https://user-images.githubusercontent.com/117919/177471793-471a83bb-9053-4ad7-8e07-28434ca41884.png)
![image](https://user-images.githubusercontent.com/117919/177471764-2f987019-dd81-40f1-b601-f0dd29875372.png)
(https://angular-v13.app.sbb.ch/angular/components/notification/examples)
With v14 this changed to some yellow:
![image](https://user-images.githubusercontent.com/117919/177471907-cf7df282-05ed-47e1-be30-ed25cd21a087.png)
(https://angular.app.sbb.ch/angular/components/notification/examples)

**Expected behavior**
Color should be unchanged.

**Comment by kyubisation** [comment]
This was changed due to accessability concerns to fulfil the minimal contrast proportion. This was suggested by our UX experts.

**Comment by daniel-sc** [comment]
Then the spec should have been updated? 
I'd consider this a breaking change - only "visually" but still..

**Comment by kyubisation** [comment]
@mcilurzo Will the spec at https://digital.sbb.ch/de/webapps/components/notification be updated?
@daniel-sc That depends very much on your definition of `breaking change`. Our view on this topic is that a color change does not affect layout rendering and is therefore not a breaking change. Color changes have also been previously applied during normal releases, although I would agree none as prominent as this.
Generally these changes are done to improve accessibility, which is not something I'm comfortable to postpone to a major release. (See https://confluence.sbb.ch/pages/viewpage.action?pageId=2016649185 for additional details.)
