### ISSUE TITLE
feat(business): header app chooser

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-angular#159]
Design Spec:
- https://digital.sbb.ch/en/webapps/modules/header (Waiting on sbb-design-systems/sbb-design-system#1)
- https://sbb.invisionapp.com/d/main#/console/17140415/385266882/inspect
- https://sbb.invisionapp.com/d/main#/console/17140415/385266879/inspect
- https://sbb.invisionapp.com/d/main#/console/17140415/385266877/inspect

API Spec:
- App Chooser should slide in from left
- App Chooser width: 300px

```html
<sbb-header>
  <sbb-app-chooser>
    <h2>Apps</h2>
    <a href="http://example.com" sbbAppChooserLink>
      <img src="..."/>
      Kurzer Name
    </a>
    <a href="http://example2.com" sbbAppChooserLink>
      <img src="..."/>
      Dies ist eine App mit einem langen Namen
    </a>
    <h2>Apps</h2>
    <a href="http://example.com" sbbAppChooserLink>
      <img src="..."/>
      Kurzer Name
    </a>
    <a href="http://example2.com" sbbAppChooserLink icon="othericon">
      <img src="..."/>
      Dies ist eine App mit einem langen Namen
    </a>
  </sbb-app-chooser>
</sbb-header>
```

**Comment by timschoch** [comment]
From a UX and Change Management perspective we really need this by the end of October. We'll run a launch campaign in November to introduce our clients to our portal. If we don't have the App Chooser implemented by then we teach them one way and then a couple weeks later they have to relearn the main way of navigating our portal.

@kyubisation @frenggi if you need help on the UX concept, let me know. We won't be able to help with the code this time around. I know the pressure you two are under, but we've got this too this time, and it's not like it's a new request... ;)

**Comment by kyubisation** [comment]
@Frenggi has provided the specification for the App Chooser. I'll try to implement it next week.
