### ISSUE TITLE
Bug: Processflow not WCAG21 compatible because of misused aria-expanded attribute

### ISSUE THREAD

**Issue by jonasch** [sbb-design-systems/sbb-angular#1617]
**Describe the bug**
When checking our application for WCAG21 criterias with TotalValidator App I stumbled across a misuse of aria-expanded for the processflow tabs. I checked your example on stackblitz and got the same result for simple example:
![image](https://user-images.githubusercontent.com/9671803/180778773-8226eacc-d0bc-49f6-84cb-df080d9f3a51.png)

The report says: _The ARIA specification only allows certain 'aria-*' attributes to be used with certain roles. See [ARIA 1.2](https://www.w3.org/TR/wai-aria-1.2/)._

**Expected behavior**
Change role or whatever is needed to be WCAG conform. As report says, the role is not correct or the attribute is misused.

**Comment by mhaertwig** [comment]
Closed by #1623
