### ISSUE TITLE
Bug: Document or implement correct usage of LoadingIndicator component

### ISSUE THREAD

**Issue by ytsurk** [sbb-design-systems/sbb-angular#1634]
As the aria-busy needs to be wrapped with aria-live for correct a11y usage,
screenreaders to not read the aria-valuetext of the LoadingIndicator component

**To Reproduce**
1. angular.app.sbb.ch
2. Navigate to LoadingIndicator component, example tab
3. Active your screenreader of joice
4. Press "Active fullbox spinner"
5. Loading, please wait is not in the Screenreader-Tree, thus not spoken.

**Expected behavior**
Screenreaders should speak the aria-textvalue provided.

**Screenshots**

**Additional context**
As the LoadingIndicator can be used for several use cases it might not be wanted to have it wrapped always with aria-live.
Also the value of aria-live might depend on the specific use cases.

Either document the need of having it wrapped into aria-live or implement an API that offers several use-cases, which can be:

- Page-Switch
- Inital Page-Load
- In-Page Load

We also implemented three states (where we change the aria-valuetext, and the wrapper also needs aria-atomic=true IMO) for the indicator:

1. Loading
2. Loading takes longer
3. Loading finished

I'm happy to create a feature request out of this ;)

**Comment by mhaertwig** [comment]
@ytsurk Thanks a lot for your input! Due to the various different use-cases I've updated the documentation and examples and did not change the functionality. Same applies to the notification component.

Please let me know if you have further input.
