### ISSUE TITLE
Bug: Processflow not working properly in Angular 14.1.4 - differences to Angular 13.15.0

### ISSUE THREAD

**Issue by david-lienberger** [sbb-design-systems/sbb-angular#1650]
The Processflow works not as it should in Angular 14.4.1

**To Reproduce**
1. Go to 'https://angular.app.sbb.ch/angular/components/processflow/examples'
2. Go to 'https://angular-v13.app.sbb.ch/angular/components/processflow/examples'
3. Compare the examples of the two versions

**Screenshots**
**Angular 14.1.4**
![grafik](https://user-images.githubusercontent.com/90822183/184582408-aedd4863-dde2-4b07-ad48-a42815203df3.png)

**Angular 13.15.0**
![grafik](https://user-images.githubusercontent.com/90822183/184582490-eb85bc39-95fd-42a4-a9b0-f4d10f593354.png)

**Additional context**
Tested in Firefox and Edge.
Already reported to @mhaertwig via mail, but did not receive an answer.

_Please fix this asap or provide a workaround._

**Comment by mhaertwig** [comment]
Thank you for the bug report and sorry for the late reply. I was not there on Friday and in meetings this morning which is why I could not answer your message earlier. We'll fix this issue with a high prio.

**Comment by mhaertwig** [comment]
Fixed in version 14.1.5

**Comment by david-lienberger** [comment]
Thank you - it works fine now.
