### ISSUE TITLE
Bug: LoadingIndicator's 3d effect not working in FF

### ISSUE THREAD

**Issue by ytsurk** [sbb-design-systems/sbb-angular#1654]
**Describe the bug**
In Firefox the 3d effect of the loading indicator is no longer visible

**To Reproduce**
1. Go to angular.app.sbb.ch (with Firefox 103.0.2)
2. Head over to the LoadingIndicator components example tab.
3. See the "flat" indicator

**Expected behavior**
The 3d effect shall be applied also in FF.

**Screenshots**
![Screenshot 2022-08-19 171339](https://user-images.githubusercontent.com/455010/185651175-0a6c14fc-65c9-493b-9ab3-52fb9b66011b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 103.0.2

**Possilbe solution**
Adding `transform-style: preserve-3d;` to `.sbb-loading-indicator > div` makes the 3d effect visible again in FF in all modes  🗡️

**Comment by jeripeierSBB** [comment]
Thanks for reporting the issue and provide a solution. PR is open.
