### ISSUE TITLE
Bug: NullInjectionException when using LightBox

### ISSUE THREAD

**Issue by ytsurk** [sbb-design-systems/sbb-angular#1656]
**Describe the bug**
When we use the LightBox compontent in a custom component, the imports specified in @NgModule did not need 
`SbbDialogModule` under the imports section.
Since version 14 this is needed.

**Expected behavior**
The migration script (13 to 14) should add the missing import, if possilbe or at least an information in the "How to update" section would be nice.
Or even better - no new import needed at all, and the LightBox compontent imports it's needs itself.

**Error message**
The error message i got started like this:
```
Error: Uncaught (in promise): NullInjectorError: R3InjectorError(AppModule)[AddressValidationService -> SbbLightbox -> Dialog -> Dialog -> Dialog]: 
  NullInjectorError: No provider for Dialog!
```

**Comment by jeripeierSBB** [comment]
@ytsurk I can't reproduce it, can you provide a stackblitz example or point me to where you use it on bitbucket? Thank you
