### ISSUE TITLE
Bug: Alignement of text and icon in buttons

### ISSUE THREAD

**Issue by railwayursin** [sbb-design-systems/sbb-angular#1657]
**Describe the bug**
Icons in buttons and text are not properly aligned, when the text is generated dynamically, e.g. using the translate library.

**To Reproduce**
See provided example on [StackBlitz](https://stackblitz.com/edit/angular-fueun6?file=src/app/button-with-icon-example.html).

**Expected behavior**
Text centered if used with icon button.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, edge
 - Version: 14.1.5

**Comment by jeripeierSBB** [comment]
It seems to be specific to your translation framework. Other evaluated expressions are working well. Basically we don't support ngx-translate, but we will have a look at it later.

**Comment by railwayursin** [comment]
Hi @jeripeierSBB

We are interested what causes the problem. Many thanks in advance for taking a deeper look.

**Comment by railwayursin** [comment]
Just detected a difference between the style classes of the two buttons: The 2nd button has additional to `sbb-button` and `sbb-button-base` the style `sbb-icon-button`. Maybe this causes the misalignment.
