### ISSUE TITLE
Bug: Radio Buttons like googly eyes

### ISSUE THREAD

**Issue by jonasch** [sbb-design-systems/sbb-angular#1694]
**Describe the bug**
On you example page the radio button look like Wackelaugen. Angular Materials look good. I am worried, that this look will be in our project, too.

**To Reproduce**
1. Go to ['Angular SBB Example Page with Radiobuttons'](https://angular.app.sbb.ch/angular/components/radio-button/examples)
3. Scroll down to 'Radio Button Group Reactive Forms Vertical'

**Expected behavior**
Nicely centered dots

**Screenshots**
![image](https://user-images.githubusercontent.com/9671803/198219339-6d4ae11d-33f6-4636-9c61-2bffc6d5640e.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Edge 106

**Comment by kyubisation** [comment]
Quick comparison: 
![image](https://user-images.githubusercontent.com/594745/198223962-7ceb1c0b-54d6-4d3b-8110-99c6ccd9d8fd.png)

Do you have any zoom enabled?

**Comment by jonasch** [comment]
i did not recognize, but yeah, you are right. sorry for that!

**Comment by kyubisation** [comment]
No problem 😃 
It's a known problem, but from our past experimentation, there is not an easy, clean solution possible, due to the rounding errors of the zoom.
