### ISSUE TITLE
Bug: Lightbox Resizing on Mobile breaks design

### ISSUE THREAD

**Issue by jonasch** [sbb-design-systems/sbb-angular#1696]
**Describe the bug**
We have seen a breaking layout of the lightbox with input fields. When we close the keyboard, the lightbox size remains and is "squashed". This happened on all Android phones and Browser we used for testing.

**To Reproduce**
1. Grab your mobile and go to ['Webshop Offers Page'](https://shop-snapshot.app.sbb.ch/offers/de/waf/ip-offers/outward?tripId=uQLwTwoCVjEasgIKOgoSCgc4NTAwMDEwEgdTVEFUSU9OEhkyMDIyLTEyLTI3VDEwOjM0OjAwKzAxOjAwIgdQTEFOTkVEKAIKVQoSCgc4NzE4MjA2YjwABDU2FTwAGjpXAAQ1MxUbACIVVwgDCh8FkxQ3NzEzMDQVVxkhAAQNtBA3Njg2MBm0Nl0ADDM6NDBKXQAkBRIXCAIQAxoGMAHxZDEiA1RHVjIEOTIxMBIXCAMQBRoGODdfTEVYHRk8Kg5QVUJMSUNfSk9VUk5FWQ%3D%3D) (valid until 27th of dec)
2. Click on any input field and wait for keyboard to show up. close keyboard and see resize not happen

With mobile on your example page you can see a quick resizing, which is also not very smooth.

**Expected behavior**
instant resize of lightbox when any overlay is closed, like the keyboard overlay.

**Screencast**
See the behaviour in our app : https://photos.app.goo.gl/BPqVdVByZTPv111DA
See the behaviour of your example with input: https://photos.app.goo.gl/BKZRpqf4QpVP57Ue7

**Smartphone (please complete the following information):**
 - Device: Android
 - Browser Chrome, Samsung, Brave, ...

**Comment by mhaertwig** [comment]
@jonasch I am not completely sure why the size is not updated in your setup. However, I think we found a workaround. 
Feel free to re-open this issue if it does not work with 14.4.0.
