### ISSUE TITLE
Bug: toggle-button-options can have different heights

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#171]
**Describe the bug**
When there is a sbb-toggle-option with a long text, the height is not the same as other sbb-toggle-options inside an sbb-toggle

**To Reproduce**
1. Go to https://angular-sbb-eh5srz.stackblitz.io
2. See the different heights of sbb-toggle-options

**Expected behavior**
Every sbb-toggle-option inside an element should have the same height as sbb-toggle

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Additional context**
We solved it for us like:
```   
    sbb-toggle {
      min-height: 4.33333em;
    }

    .sbb-toggle .sbb-toggle-option-button {
      min-height: unset;
      height: calc(100% - 5px);
    }
```

**Comment by kyubisation** [comment]
For some reason I can't open the provided link.
This link works: https://stackblitz.com/edit/angular-sbb-eh5srz
