### ISSUE TITLE
Feature request: Larger click area for tooltip icons

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#175]
**Is your feature request related to a problem? Please describe.**
In our application we want the tooltip to have a larger click area (the whole width of the cell) than the actual icon. In the screenshot below the current click area is red, our desired click area is green:
![image](https://user-images.githubusercontent.com/117919/65231066-49a2c400-dacf-11e9-98f5-34d198064367.png)

**Describe the solution you'd like**
* Have the button inside the tooltip fill the complete tooltip size
* Assure tooltip icon and tooltip content is centered.

**Describe alternatives you've considered**
Bevore the latest release we had the following workaround:
```scss
::ng-deep .sbb-tooltip-trigger {
  width: 100%;
}
```

**Comment by timschoch** [comment]
Alternatively, if we can change the tooltip trigger to a custom element instead of the icon, that would work too.

**Comment by jeripeierSBB** [comment]
Is now more easily possible with the @sbb-esta/angular library by setting width via `.sbb-tooltip-trigger` (use ng-deep). Alternatively, the directive usage could be considered. 
Please reopen if this is not enough for your use case.
