### ISSUE TITLE
ConnectedPositionStrategy for Dialogs

### ISSUE THREAD

**Issue by teebee78** [sbb-design-systems/sbb-angular#1758]
When opening a dialog with the class SbbDialog, currently it is only possible to set the position of the dialog (SbbDialogPosition). In our (SBB) application we would like to open the dialog close to the element that triggerered the opening. In Anguler CDK, it's possible to use the PositionStrategy FlexibleConnectedPositionStrategyOrigin for that. This should also bei supported by the esta angular librarry. 

Futhermore, it would be really cool, it there was a little triangle that points to trigger - as in the tool tips.

**Comment by kyubisation** [comment]
Hello @teebee78 
That is not intended with this design pattern. Please use the tooltip for this purpose.
