### ISSUE TITLE
Bug: vertical form field sbb-error clash

### ISSUE THREAD

**Issue by kirill1722** [sbb-design-systems/sbb-angular#1768]
Describe the bug
User can't see multiple errors or long error messages correctly when using vertical form group.

To Reproduce
https://gvz5z5run-bkmr--4200.local-credentialless.webcontainer.io

<img width="280" alt="image" src="https://user-images.githubusercontent.com/28723230/211016306-e24d3e28-3657-45c8-9fab-c25fdeed9598.png">

**Comment by kyubisation** [comment]
This behavior (and possible options) is documented in https://angular.app.sbb.ch/angular/components/form-field/overview (See `Error messages`).

**Comment by kirill1722** [comment]
It works with sbb-form-field-flexible-errors class. Thank you
