### ISSUE TITLE
Bug: Loading Indicator 'fullbox' should cover parent, but does not

### ISSUE THREAD

**Issue by jonasch** [sbb-design-systems/sbb-angular#1791]
**Describe the bug**

**To Reproduce**
1. Go to ['my stackblitz example'](https://stackblitz.com/edit/angular-egsbjc?file=src%2Fapp%2Floading-indicator-fullbox-example.html,src%2Findex.html)
2, Scroll to button
3. Click on Button
4. See loading indicator only covering the view width/height, but not the complete parent (images should both be covered)

**Expected behavior**
Complete screen should be covered by loading indicator

**Comment by jeripeierSBB** [comment]
Hi @jonasch. I think, the issues is solved, if you put `position: relative;` on your parent element.

**Comment by jeripeierSBB** [comment]
I don't know how we should solve it in another way. To stick it to the parent we need to position it absolute. And this always needs a reference which is positioned absolute or relative. If non is given, it falls back to the body. But we are open for good ideas :D As an, in my eyes, over engineered solution, we could provide a directive which just sets the position relative. We will discuss it. @mhaertwig @kyubisation

**Comment by kyubisation** [comment]
We have added a note in the documentation on how to handle this situation. We understand that this is not the nicest solution, but creating a separate component/directive seems a little bit like an overkill (and also UX does not like the `fullbox` pattern).
