### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by i7i5** [sbb-design-systems/sbb-angular#1797]
Hi there,

we'll update our node version to 18 next PI. On local testing I got the following issue:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sbb-esta/angular@15.1.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0 <17.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```
Could you pls raise the node version requirements to 18?

Thanks a lot :)

**Comment by kyubisation** [comment]
See #1795
This was released on friday.
Please re-open if you have any additional questions in this regard.

**Comment by i7i5** [comment]
Perfect, I didn't check the new lib version. Thanks a lot :)
