### ISSUE TITLE
Bug: Release 14.4.1 broken: dependency on angular cdk 15

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1798]
**Describe the bug**
v14.4.1 has a peer dependency to angular 15

**To Reproduce**
1. create an angular 14 project
2. install this lib in 14.4.1
3. observe that an incompatible peer dependency to @angular/cdk ^15 is a problem

**Expected behavior**
v14 from this lib should not (peer) depend on angular 15

**Desktop (please complete the following information):**
 - OS: win10
 - Browser n/a
 - Version SACL 14.4.1

**Additional context**
I suspect this change to be the problem: https://github.com/sbb-design-systems/sbb-angular/compare/14.4.0...14.4.1#diff-5ef0ea9ea291d74d4ad4ad321d0aea5488a66ea0560aff9eb210911b6809bbe2

**Comment by mhaertwig** [comment]
@daniel-sc thanks for the bug report! I just fixed it and published v14.4.2.
