### ISSUE TITLE
Bug: SbbDialog not diaplayed correctly

### ISSUE THREAD

**Issue by magana49** [sbb-design-systems/sbb-angular#1803]
**Describe the bug**
we use the sbbDialog component with content and an action bar. 
when the browser window reaches a particular height, the action bar is no longer properly displayed (look at attached image)

**To Reproduce**
1. go to https://angular.app.sbb.ch/angular/components/dialog/examples
2. open the Dialog in the 3rd example
3. make the browser window smaller (height) until the button start to disapear

**Expected behavior**
the action bar is properly displayed no matter the height of the window
the content of the dialog is scrollable

**Screenshots**
![image](https://user-images.githubusercontent.com/62182007/215726666-7d251bd9-57d9-4119-a150-a6c4d74f904e.png)

![image](https://user-images.githubusercontent.com/62182007/215724481-7e47a96f-c64f-4137-ba50-9887698e60f3.png)

**Desktop (please complete the following information):**

OS: Windows
Browser: chrome (109.0.5414.120) and firefox (109.0)
Version of Angular 14.0.4,
Version of SBB Library: 14.1.3

**Comment by mhaertwig** [comment]
Hi @magana49, can you please provide information about the browser, device and operating system you are using?

**Comment by magana49** [comment]
Hi @mhaertwig, sorry, I just updated the post with the information.

**Comment by mhaertwig** [comment]
@magana49 We've just published [Release 14.4.3](https://github.com/sbb-design-systems/sbb-angular/releases/tag/14.4.3) with a fix.
