### ISSUE TITLE
Bug: @sbb-esta/angular documentation page redirecting to home

### ISSUE THREAD

**Issue by Arini11** [sbb-design-systems/sbb-angular#1822]
https://angular.app.sbb.ch/angular is redirecting to https://angular.app.sbb.ch, I can not read the documentation.

1. Go to https://angular.app.sbb.ch
2. Click on @sbb-esta/angular on the left side menu
3. See how it doesn't load the requested page, and stays in the same page

**Expected behavior**
The page is expected to load.

 - OS: Windows10
 - Browser: Chrome
 - Version: Latest

**Additional context**
Yesterday it was working well.

**Comment by kyubisation** [comment]
We downgraded our showcase to version 15.4.1, which does not have this problem. We will analyze this problem and fix it as soon as possible.
