### ISSUE TITLE
[Bug]: Tooltip disable not working

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#1855]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

15.4.1

### Operating system

Win 10

### Browser / Browser version

Chrome 111

### Input mode

Mouse/Keyboard

### What happened?

Using the input/attriubte `disabled` on `SbbTooltipWrapper` the tooltip is shown on hover. 

Expected behavior: Tooltip does not open when disabled=true and tooltip icon is in a disabled state (visually).

### Steps to reproduce the issue

https://stackblitz.com/edit/angular-1wx9ir?file=src/app/tooltip-simple-example.html

**Comment by mhaertwig** [comment]
@mcilurzo is there a design specification that describes how a disabled [tooltip-button](https://angular.app.sbb.ch/angular/components/tooltip/examples) should look?

I could e.g. use the styling of the disabled ghost button (iron color in lean mode and hidden in standard mode).
