### ISSUE TITLE
[Bug]: invalid import statement in class file lightbox.mjs

### ISSUE THREAD

**Issue by ziggych** [sbb-design-systems/sbb-angular#1872]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

15.9.0

### Operating system

Windows 10

### Browser / Browser version

Chrome Version 112.0.5615.86

### Input mode

None

### What happened?

The file \node_modules@sbb-esta\angular\\fesm2020\lightbox.mjs has an error, more precisely the following statement:
`import { Subject, defer, of, takeUntil, startWith as startWith$1 } from 'rxjs';`
This line produces the following error messages during the build on jenkins, or with 'ng serve' locally:
Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs'.
Error: export 'startWith' (imported as 'startWith$1') was not found in 'rxjs'.

Affected application: https://code.sbb.ch/projects/KI_FZF/repos/fzf-webapp/ 

### Steps to reproduce the issue

1. Create angular project
2. ng add @sbb-esta/angular
3. Find the generated file my-angular-project\node_modules\@sbb-esta\angular\fesm2020\lightbox.mjs

### Relevant log output

```shell
./node_modules/@sbb-esta/angular/fesm2020/lightbox.mjs:1020:39-48 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableOb
servable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualActio
n, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, 
generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

./node_modules/@sbb-esta/angular/fesm2020/lightbox.mjs:1020:67-78 - Error: export 'startWith' (imported as 'startWith$1') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, Connectable
Observable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAct
ion, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern
, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

× Failed to compile.
```

**Comment by jeripeierSBB** [comment]
Hi @ziggych, which rxjs version do you use?
