### ISSUE TITLE
[Feature request]: Add and remove Tabs 

### ISSUE THREAD

**Issue by nitesis** [sbb-design-systems/sbb-angular#1896]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

**Lean Web**

Erweiterung des Tabsystems im Lean Web um die Optionen 

- Tabs hinzuzufügen (+ mit optional Label)
- Tabs wieder entfernen via Hover (hier wird x zum schliessen angezeigt)
- Tabs hinzufügen Label via Eingabemaske Textinput oder Dropdown

### Link to design proposal file

https://www.figma.com/file/dZBw8uHjKY31RP9NjxoPT8/WebApp-GS?node-id=604%3A90106&t=O6ONA0VFV7mlWVQD-1

**Comment by mhaertwig** [comment]
@nitesis Dieses Verhalten lässt sich mit der aktuellen Funktionalität von SBB Angular umsetzen. Hier ein minimales Beispiel: https://stackblitz.com/edit/4kpxjv

Damit das Icon klickbar ist, muss es in einen Button gesteckt werden. Anschliessend muss der Button minimal gestyled werden, damit er keinen Rahmen und die gleiche Höhe wie das Icon hat. Auch die Funktionalität zum Anzeigen des Buttons bei Hover liesse sich über das Styling lösen.

Hilft dir das weiter?

**Comment by nitesis** [comment]
Hi @mhaertwig 
Danke für die Rückmeldung. Werde das an unsere Entwickler so weitergeben. Bei Fragen melde ich mich.
Danke und einen schönen Feiertag.

**Comment by mhaertwig** [comment]
Hi @nitesis 
Alles klar. Dann schliesse ich deinen Feature Request vorerst. Wenn du oder die Entwickler fragen haben, könnt Ihr gern auf mich zukommen. Ich wünsche dir auch einen schönen Feiertag.
LG, Mario
