### ISSUE TITLE
Bug: Sbb Icon House not rendered properly on MS Edge

### ISSUE THREAD

**Issue by filip-belos** [sbb-design-systems/sbb-angular#191]
**Describe the bug**
<sbb-icon-house></sbb-icon-house> is not rendered properly on MS Edge. 

**To Reproduce**
1. We are using the icon inside sbb breadcrumb component which is not rendered properly on MS Edge in any case. See attached screenshot and code snippet.

`<sbb-breadcrumbs>
  <sbb-breadcrumb>
    <a routerLink="/" routerLinkActive="sbb-selected">
      <sbb-icon-house></sbb-icon-house>
    </a>
  </sbb-breadcrumb>
  <sbb-breadcrumb>
    <a class="breadcrumb-link" routerLink="/" routerLinkActive="sbb-selected">
      {{'INFO-PAGE.TITLE' | translate}}
    </a>
  </sbb-breadcrumb>
  <sbb-breadcrumb>
    <a class="breadcrumb-link" routerLinkActive="sbb-selected" routerLink="{{pageUrl}}">
      {{translationsMappings[childUrl] | translate}}
    </a>
  </sbb-breadcrumb>
</sbb-breadcrumbs>`

**Screenshots**
![image-2019-10-02-13-29-47-457](https://user-images.githubusercontent.com/34233022/66131841-67eee080-e5f4-11e9-9ff6-075e83280140.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser MS Edge
 - Version Microsoft Edge 42.17134.1.0

**Smartphone (please complete the following information):**
 N/A

**Comment by kyubisation** [comment]
Have you configured the width and height of the icon?

**Comment by jeripeierSBB** [comment]
This should be fixed with Chromium Edge
