### ISSUE TITLE
Bug: sbb-textarea doesn't support bigger height correctly

### ISSUE THREAD

**Issue by justynarejek-sbb** [sbb-design-systems/sbb-angular#194]
**Describe the bug**
When sbb-textarea size is bigger than one line, only click on first line activate it.
In addition, saving such resized field and opening it results in only first line of field visible.

**Expected behavior**
Clicking anywhere in textarea activate it.
Multiple lines of text are visible after save.

**Screenshots**
![textarea](https://user-images.githubusercontent.com/56348409/66479287-804f7700-ea9c-11e9-955e-35e2de1c080e.gif)

**Comment by kyubisation** [comment]
Thank you for bringing this to my attention.
My recommendation would be to use the native textarea, unless you specifically need the character counter.
