### ISSUE TITLE
[Bug]: sbb-tab-link active state seems to not work properly

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#1941]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

16.3.0

### Operating system

macOS 13.4.1

### Browser / Browser version

Chrome/Safari

### Input mode

Mouse/Keyboard

### What happened?

When using the [tabs](https://angular.app.sbb.ch/angular/components/tabs/examples) component in combination with routing, the active state doesn't properly work. Only the focus state seems to work.

Using native anchor tags without the `sbb-tab-link` directive works perfectly fine (see second snippet in repro).

### Steps to reproduce the issue

```
<nav sbb-tab-nav-bar [tabPanel]="tabPanel">
  <a sbb-tab-link routerLink="route-1" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">route 1</a>
  <a sbb-tab-link routerLink="route-2" routerLinkActive #rla="routerLinkActive" [active]="rla.isActive">route 2</a>
</nav>
<sbb-tab-nav-panel #tabPanel>
  <router-outlet />
</sbb-tab-nav-panel>
```

This works:
```
<nav sbb-tab-nav-bar [tabPanel]="tabPanel">
  <a routerLink="route-1" routerLinkActive="active" #rla="routerLinkActive">route 1</a>
  <a routerLink="route-2" routerLinkActive="active" #rla="routerLinkActive">route 2</a>
</nav>
<sbb-tab-nav-panel #tabPanel>
  <router-outlet />
</sbb-tab-nav-panel>
```

**Comment by sandrooco** [comment]
I'm currently trying to create a repro stackblitz but am stuck on the icon registry that wants a HttpClient.

> Error: Could not find HttpClient provider for use with Sbb Angular icons. Please include the HttpClientModule from @angular/common/http in your app imports.


Maybe you can already read something out of it: https://stackblitz.com/edit/stackblitz-starters-ys2bad?devToolsHeight=33&file=src%2Fapp.component.html

**Comment by sandrooco** [comment]
Another finding: providing the `[active]` attribute/input "manually" via `activatedRoute` works:
```
 <a
    sbb-tab-link
    routerLink="route-1"
    routerLinkActive
    #rla="routerLinkActive"
    [active]="(activatedRoute.firstChild.url | async).toString().includes('route-1')"
  >route-1</a>
```

Obviously not a solution but maybe it helps you.

**Comment by mhaertwig** [comment]
@sandrooco, thanks for creating the issue. I analyzed this and came to the solution that it's not a bug.

To make your example working you need to make sure, that the `routerLinkActive` reference is unique.
```
  <a sbb-tab-link routerLink="route-1" routerLinkActive #rla1="routerLinkActive" [active]="rla1.isActive">route 1</a>
  <a sbb-tab-link routerLink="route-2" routerLinkActive #rla2="routerLinkActive" [active]="rla2.isActive">route 2</a>
```
(`rla1` and `rla2` instead of just `rla`). 

Here's a working example: https://stackblitz.com/edit/stackblitz-starters-dkl884?file=src%2Fapp.component.html

In our code example in the angular documentation, we wrap the `sbb-tab-link` in an `ngFor` directive which has its own template scope. Therefore, we can just use `#rla`. I'll add a hint to our documentation to make this more clear.

Hope this helps

**Comment by sandrooco** [comment]
Well that totally makes sense, should have found that on my own..
Thank you for the quick response and even clarification in the docs!
