### ISSUE TITLE
[Bug]: Checkbox should ignore click events on input change

### ISSUE THREAD

**Issue by i7i5** [sbb-design-systems/sbb-angular#1961]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

16.4.0

### Input mode

None

### What happened?

As we're implementing a new feature I tried to implement the following functionality:
There is only one checkbox which can have 3 states:

- checked
- unchecked
- indeterminate

The initial state depends on our calculation, so it can be any of these three. In addition it should be possible to click through the states like: unchecked *click -> checked *click -> indeterminate *click -> unchecked *click -> checked.

This isn't possible atm because the checkbox only knows the state "checked = true/false". If you click and modify the states programmatically the click event overrides the state calculated on change event.

The following example shows this behavior and the workaround we implemented: [https://stackblitz.com/edit/zsbnnh?file=src%2Fapp%2Fcheckbox-indeterminate-state-example.html,src%2Fapp%2Fcheckbox-indeterminate-state-example.ts](https://stackblitz.com/edit/zsbnnh?file=src%2Fapp%2Fcheckbox-indeterminate-state-example.html,src%2Fapp%2Fcheckbox-indeterminate-state-example.ts). As a workaround we use the click event and disable the default behavior `event?.preventDefault();`.

I think there should be a way to kind of disable the click handling or proper implementation of the 3 states a checkbox can have.

Thanks a lot and kind regards
i7i5

### Steps to reproduce the issue

See description above and stackblitz: [https://stackblitz.com/edit/zsbnnh?file=src%2Fapp%2Fcheckbox-indeterminate-state-example.html,src%2Fapp%2Fcheckbox-indeterminate-state-example.ts](https://stackblitz.com/edit/zsbnnh?file=src%2Fapp%2Fcheckbox-indeterminate-state-example.html,src%2Fapp%2Fcheckbox-indeterminate-state-example.ts).

**Comment by jeripeierSBB** [comment]
Hi @i7i5, thanks for creating the issue. We would like to better understand what's the business use case for that? When should a user set indeterminate himself?

So far we consider the indeterminate state like when you have a group of checkboxes and it's kind of a summary of the group. So if you have a some checked and some unchecked, the group state would be indeterminate.

**Comment by mhaertwig** [comment]
Hi, thanks for creating the issue. I just had a call with @jeripeierSBB and explained everything to him.
We're both not sure if it is intended to select indeterminate states with a single checkbox. I'll try getting feedback from the UX team and update this issue afterwards.

**Comment by mhaertwig** [comment]
@mcilurzo, should it be possible to select indeterminate states with a single checkbox? 

E.g. 1st click: indeterminate >> 2nd click: checked >> 3rd click: unchecked

Currently, the indeterminate state only exists for multiple checkboxes.

**Comment by mcilurzo** [comment]
From a UX perspective, it makes no sense to allow this behaviour. The behaviour of a basic component should be the same across the entire web world. The chance that a user will not understand or recognise this behaviour seems very high to me. My recommendation is not to implement this CR. I am sure that the problem can be solved in a other/better way in the UI.

**Comment by mhaertwig** [comment]
Thanks for the explanation.
@i7i5, I am closing this issue after this feedback. 

@mcilurzo also pointed me to this documentation: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#:~:text=it%20cannot%20be%20set%20using%20an%20HTML%20attribute
