### ISSUE TITLE
[Feature request]: Ability to set the label for sbb-file-selector

### ISSUE THREAD

**Issue by dennis-eichardt-sbb** [sbb-design-systems/sbb-angular#1969]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

For my application I would need the ability to set the label text for the sbb-file-selector. So that users see e.g. “upload”, “telechargez” etc. in their native languages.

As a workaround, we developers tried to do reach this the hacky way: Changing text content, overwriting private properties, etc. → it was not possible. The component keeps the value that has been set but is not rendered like that. We even played with application lifecycles to make it work - no change possible.

So I would like to request a feature that enables me to set the label text for the sbb-file-selector, so we can integrate into our application swiftly.

**Comment by dennis-eichardt-sbb** [comment]
Addendum to clarify (since a colleague pointed it out): I would like to use an already translated label and remove the icon.

**Comment by mhaertwig** [comment]
Sorry for my delayed reply.

I had a look at your app and found out that the translation should already work for the labels in the `sbb-file-selector`. If you want to customize the label, you can add the strings to the `messages.{de,en,fr,it}.xlf` under `/zvs-businessmanager-frontend/src/i18n/`:

```
<trans-unit id="sbbFileSelectorUploadFile" datatype="html">
  <source>Upload file</source>
  <target state="translated">Datei hochladen</target>
</trans-unit>
```
When you build the app, the localized bundle under `/dist/{de,fr,it}` will contain the customized string.

Does this help you?

**Comment by mhaertwig** [comment]
As discussed internally, everything works now. I am closing this issue.
