### ISSUE TITLE
Feature request: Select on focus

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#197]
**Is your feature request related to a problem? Please describe.**
We regularly have the requirements to select all existing text in input components when they are focused. 

**Describe the solution you'd like**
We'd like a directive that easily allows to toggle if text should be selected on focus - e.g. `selectOnFocus`.

**Describe alternatives you've considered**
We will build this directive in our project.

**Additional context**
If you like this directive to be included (in whicht project?), I'll create a PR.

**Comment by kyubisation** [comment]
I'll discuss this in my next meeting with UX.

**Comment by kyubisation** [comment]
Do you require this to be on tab navigation or also on click? We are divided on whether click should be supported, since we are not aware of any other implementation doing this.

**Comment by daniel-sc** [comment]
Hi @kyubisation ,

it seems meaningful to  go for the "focus" event (click and tab) - the following implementation would exactly do this:

```ts
@Directive({
  selector: 'input[appSelectOnFocus]'
})
export class SelectOnFocusDirective {

  constructor(private el: ElementRef) {
  }

  @HostListener('focus')
  onFocus(): void {
    const input: HTMLInputElement = this.el.nativeElement;
    input.select();
  }

}
```

**Comment by jeripeierSBB** [comment]
After reviewing this again, we are uncertain whether this should belong to sbb-angular or should be done in consuming project if needed. 
@daniel-sc, do you see an argument why this should be in our library?

**Comment by daniel-sc** [comment]
If we are the only application that uses this, there is no need for it to be part of the library. 

I'd think that other apps would have need for this as well - if this is true, it'd be easier to maintain in a single place..

**Comment by jeripeierSBB** [comment]
For now we would like to close this issue, but if more demand is upcoming we will re-consider this request.
