### ISSUE TITLE
Feature request: dropdown / contextmenu is missing category/sub-title labels

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#201]
**Is your feature request related to a problem? Please describe.**
The usermenu and contextmenu do not yet support the insertion of sub titles / categories - see screenshots:
![image](https://user-images.githubusercontent.com/117919/67395675-aef24500-f5a6-11e9-99fe-450955491516.png)
![image](https://user-images.githubusercontent.com/117919/67396328-aa7a5c00-f5a7-11e9-969b-039c934a0b37.png)

**Describe the solution you'd like**
Implemented as in design system. Optimally, the labels would allow to contain custom elements.

**Comment by jeripeierSBB** [comment]
Can be achieved by using `<span class="sbb-label">Title</span>`. We will add a margin definition for labels which are not at the beginning ("Group 2" in the above example).
