### ISSUE TITLE
Feature request: Icon Bar for Business Layout

### ISSUE THREAD

**Issue by timschoch** [sbb-design-systems/sbb-angular#203]
**Is your feature request related to a problem? Please describe.**
The four column Layout defined with @frenggi has an Icon Bar on the left.
We need this for the next step of our client portal.

**Describe the solution you'd like**
Here is our suggestion for a first implementation:
https://xd.adobe.com/view/9f2079bc-c495-41e5-7648-b27dcfd25d4b-e911/screen/0057cb7c-87a0-4bd0-b581-d51643d297d6/AK-Icon-Bar
https://xd.adobe.com/view/9f2079bc-c495-41e5-7648-b27dcfd25d4b-e911/screen/cfdddd07-b252-4e4f-8e49-24f73c108519/AK-Icon-Bar-Animation

**Additional context**
We'll build this in an upcoming sprint. Unfortunately we don't have the time to code this up to SACL standards. Would you like us to create a PR nonetheless and submit what we have as a starting point?

**Comment by kyubisation** [comment]
That would be appreciated 😃 
Is this going to be included in digital.sbb.ch?

**Comment by timschoch** [comment]
@frenggi and I came up with the concept together, the goal is to make the whole layout available to all at some point in the future, along side the header, this icon bar and the content panes.

**Comment by kyubisation** [comment]
Closed via #600
