### ISSUE TITLE
Bug: Header space too big when resizing web page on IE11

### ISSUE THREAD

**Issue by davide1995** [sbb-design-systems/sbb-angular#204]
**Bug description**
Following repository (https://github.com/davide1995/sbb-easy-header) use the sbb-header from the sbb-business API. It's a small project used only for this example. When we resize the webpage using IE11 clicking on the button "Click me" doesn't work.

**To Reproduce**
1. Clone the repo
2. npm install
3. ng serve
4. Open IE11
5. Navigate on http://localhost:4200
6. Resize the webpage
7. Click the "Click me" button. Click on the right side

Stackblitz freeze under IE11 so I can't provide an online example. Just clone on local the repository and serve the angular project.

**Expected behavior**
"Click me" should light up as we click a normal button.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Comment by kyubisation** [comment]
It appears to be related to the icon. Limiting the height of the icon seems to fix the issue. I will fix this in the next release.
Workaround (in styles.(s)css):
```css
sbb-header .sbb-header-logo {
  height: 54px;
}
```
