### ISSUE TITLE
Feature request: Dropdown Component

### ISSUE THREAD

**Issue by mischahaenen** [sbb-design-systems/sbb-angular#207]
**Bug**
The size of the dropdown field is determined by the currently selected object. If the object is short, long texts in the dropdown are truncated. 

![Dropdown-Component](https://user-images.githubusercontent.com/31645541/67571162-8a77a380-f733-11e9-9d09-a90e9569cace.png)

**Comment by kyubisation** [comment]
This should be fixed with the new `menu` module in the merged library/package.
