### ISSUE TITLE
[Feature request]: Tag with Icon

### ISSUE THREAD

**Issue by Frenggi** [sbb-design-systems/sbb-angular#2072]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

Currently the tag component only allows text inside. It would be great to have a tag enhanced with icon. The configuration should the following variants: text only, icon with text, icon only. Also whether or not displaying the amount should be configurable.
Lyne design system currently allows all these variants, but the "icon only" variant seems to be fixed (paddings).

**Comment by mcilurzo** [comment]
To maintain consistency between the Angular Library and Lyne, I suggest we implement this feature request. Here are the design variants: https://www.figma.com/file/97aIxaMIDQIEK5Pq4lkUlQ/Lean-2.0-(Beta)?type=design&node-id=528%3A154404&mode=design&t=AYdSaksr5XTEkxoZ-1
