### ISSUE TITLE
[Bug]: New Icons not behaving the same way as the old ones 

### ISSUE THREAD

**Issue by mircmo** [sbb-design-systems/sbb-angular#2094]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

16.X & 17.X

### Input mode

None

### What happened?

Hi there
This is probably neither *really* a bug nor is it something you can fix in the angular library, but since the behaviour changed with the new icons i thought i will report this here, because you'll probably know who's responsible for these things. 

The problem is that the the SVG-paths of the new icons are somewhat different to before and now adding custom styles like fill works no longer.

It's probably easiest to show an example: https://stackblitz.com/edit/stackblitz-starters-2rybin?file=src%2Fmain.ts 

As you can see fill worked before but doesn't anymore. One change was, that several icons changed from a `<polygon>` to a `<path>`, which is why some of our css selectors didn't work anymore, but this was an easy fix. However the bigger problem is, that for some icons fill just doesn't work at all anymore. This is probably because of how the path is constructed, so now the fill algorithm is no longer able to figure out what areas of the path should be filled. Playing around with SVG [fill-rule](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule) doesn't change anything. 

For these cases we changed back to the kom icons, since as far we know these won't get removed in the future. 

Regardless of that I wanted to report this since one of the advantages of directly embedding the icons as SVG-elements is to be able to style them via CSS and this is quite limited if the fill doesn't work anymore. I don't know if all icons are affected, i just tested the ones where we applied some custom fills. And since in these two examples, the icons look the same as before, they effectively just got worse to use with no real change.

### Steps to reproduce the issue

See Stackblitz

**Comment by mcilurzo** [comment]
It is not allowed to manipulate the icons in this way. The color is an exception. There are a few icons that have a status, e.g. the star or the heart icon. These are available in the official icon library (heart-filled-small, star-filled-small). Depending on the status (liked or not liked), the appropriate icon should be loaded. The "circle-plus-medium" icon should not be changed. May I ask where and in what way this is planned?

(Filled star icon in Figma: https://www.figma.com/file/UQBd7cHKav0hr9oXYp7opJ/SBB-Icons?type=design&node-id=372%3A1866&mode=design&t=a8pKrV5qwL20RNdL-1)

**Comment by mircmo** [comment]
<img width="317" alt="image" src="https://github.com/sbb-design-systems/sbb-angular/assets/61457049/34828741-987c-4e40-aacf-c4f0969c956a">  

Our use case is something like the above. When we hover on an item, a plus icon appears at the top and to the bottom so the user can click it to add content above or below. In this image you can see we added a white background to the circle because otherwise you could see the blue horizontal line in the background. 

But yeah we could also implement this by just using the normal plus icon, downsize it and add a border with border radius on the container of the icon to get around this. 

As for the star icon you are right, the new icons now have a filled variant, we didn't notice that. So we could implement this with hiding one or the other icon depending on the state.

**Comment by mhaertwig** [comment]
I am closing this issue. Feel free to re-open if you don't agree.
