### ISSUE TITLE
[Bug]: Lean Content Sprachauswahl

### ISSUE THREAD

**Issue by u201301** [sbb-design-systems/sbb-angular#2105]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Input mode

None

### What happened?

Verhalten des Contents Sprachauswahl von "mouse-over" nicht gemäss Definition - siehe Printscreens.

![email_bug_content](https://github.com/sbb-design-systems/sbb-angular/assets/153168666/5057fffe-bd8d-4ba3-96dd-ffa236149b22)
![printscreen2](https://github.com/sbb-design-systems/sbb-angular/assets/153168666/576a69fa-9431-46e1-a5ff-80043cb476d7)

### Steps to reproduce the issue

1. Step one
2. Step two
3. ...

**Comment by mcilurzo** [comment]
this was not intended, i think the current implementation is a bug. Your suggestion seems good, it can be implemented that way.
