### ISSUE TITLE
[Bug]: Is the current active state of the tag component correct?

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#2119]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Your Question

Is the current active state of the tag component correct?

### Give us a summary about your question

This is a very minor detail - we actually got user feedback about it which is the reason why I'm creating this issue.

When clicking/activating a [tag item](https://angular.app.sbb.ch/angular/components/tag/examples), the border will be gray (which is a focus state i suppose?) but it stays like this until the user clicks anywhere else. If a user clicks 3/5 tags, one will have a different ui state than the two others, effectively leading to 3 different states (default, active and "last active").

Is this done on purpose?

I tried to capture this behavior in a quick screen recording:
https://github.com/sbb-design-systems/sbb-angular/assets/25688064/28bcd7e3-3f3b-4a06-8b3f-217738f8765c

**Comment by mhaertwig** [comment]
Hi @sandrooco 
Thank you for your feedback and for the detailed issue. The behavior you describe is not like this on purpose. I marked this issue as a bug and we'll fix it as soon as possible. I'll keep this issue updated.
Regards, Mario
