### ISSUE TITLE
[Question]: Sidebar component - position and multiple bars

### ISSUE THREAD

**Issue by LElbert** [sbb-design-systems/sbb-angular#2130]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Your Question

Sidebar component - position and multiple bars

### Give us a summary about your question

I'm an external employee currently working on an Angular WebApp. I'm trying to use the [Sidebar](https://angular.app.sbb.ch/angular/components/sidebar/overview) component but face some difficulties and would like to ask if you think it's possible for my use case or whether I should rather fall back on the Angular Material Components or implement my own?

The two use cases I try to evaluate:

- Two sidebars. One on the left side and one on the right side of the screen.
- Only one sidebar but on the right side of the screen.

In a first try I did not succeed in implementing neither of the two use cases with the SBB Angular Sidebar. I tried to adapt the Stackblitz-Examples from the documentation to my use cases but did not really succeed. It seems to me the sidebar only supports a single sidebar (not two of them) and I did not succeed in bringing it to the right handside either.

I wonder if there is an easy way to achieve the above mentioned use cases with the SBB Angular Sidebar or if it easier for me to fall back on the Angular Material components and adapt SBB Styles manually?

Best
Lucas

### Provide as much useful information as you can

![SidebarLeftRight](https://github.com/sbb-design-systems/sbb-angular/assets/147694361/1719fde9-b9c6-4f92-a443-73d067ead53b)
![SidebarRight](https://github.com/sbb-design-systems/sbb-angular/assets/147694361/361da16a-a608-46c6-af58-fc32d649f68b)

**Comment by RTdeveloper2** [comment]
<div class="container">
      <app-left-sidebar></app-left-sidebar>
      <div class="main-content">Main Content</div>
      <app-right-sidebar></app-right-sidebar>
    </div>
in app component.ts file, the above approach is not working?

**Comment by mhaertwig** [comment]
Hi @LElbert 

Currently, positioning an SBB Angular Sidebar on the right side of the screen is not supported. It would require some functional changes in the library.

I can convert your issue into a feature request, however we're currently low on resources and I cannot tell when we'll have time to implement it. Moreover, I would need feedback from our UX Team (@mcilurzo, fyi) before. The SBB Design System only specifies sidebars that are positioned on the left side of the screen.

Regards, Mario

**Comment by LElbert** [comment]
@RTdeveloper2 Thanks for the suggestion, I will see if I can get that to work :)
@mhaertwig Okay, I understand.

I will see if I can get RTdeveloper2's suggestion to work or otherwise continue with the default Angular Material sidebar/drawer.

**Comment by mcilurzo** [comment]
Here the new variant: https://www.figma.com/file/97aIxaMIDQIEK5Pq4lkUlQ/Lean-2.0-(Beta)?type=design&node-id=6526%3A14711&mode=design&t=AYdSaksr5XTEkxoZ-1
