### ISSUE TITLE
[Feature request]: Customizable default Icon for sbb-icon

### ISSUE THREAD

**Issue by U239087** [sbb-design-systems/sbb-angular#2132]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

Recently I was in need of a default icon while using the sbb-icon element. Sadly this is not an option as far as I can see at the moment. At first I imagine this to be a string-input like this:
```html
<sbb-icon svgIcon="this-icon-doesnt-exist" defaultIcon="train-small" />
```

But I personally would also be fine with adding a new method to the iconRegistry like "addDefaultSvgIcon()" where you could define a specific icon via SafeResourceUrl.

**Comment by U239087** [comment]
Although that json file is possibly useful in this matter, that's not what I'm proposing.
What I'm asking for is an actual new property on the sbb-icon element that allows someone to define an icon that is displayed if an invalid name for an icon was given in the "svgIcon" property.

**Comment by jeripeierSBB** [comment]
I did understand your proposal, but my question back is, how can you get into a situation where an invalid icon name is given?

**Comment by U239087** [comment]
Our users can provide an icon name via json file. So there's a possibility that an incorrect name is given. A typo for example

**Comment by jeripeierSBB** [comment]
After discussion with @mhaertwig and @kyubisation we would not like to implement such a feature as it is highly specific. But there would be an easy work around for it:
You can just call SbbIconRegistry.getNamedSvgIcon() and check the result. The icon would be cached anways, so it will be loaded at maximum once.
@mhaertwig create a stack blitz (thanks!): https://stackblitz.com/edit/umjprg?file=src%2Fapp%2Ficon-simple-example.html,src%2Fapp%2Ficon-simple-example.ts,src%2Fapp%2Fapp.module.ts

would this solve your use case in an acceptable way?

**Comment by U239087** [comment]
This would be useful for a one-off icon display. But if the icon gets displayed in, for example, five different components, I would have to create a wrapper component to override the icon name before it is displayed. That's why I would be a fan of having a property or method on the registry that allows me to set a default icon.
I'm fine with doing it the way you explained, but I can imagine this is a problem for anyone that stores icon names in a database or retrieves them from API calls.

**Comment by jeripeierSBB** [comment]
You could just write a pipe with the same logic which is currently in the component of the stackblitz example.

e.g. `<sbb-icon [svgIcon]="myIcon | validateIcon | async">`

**Comment by U239087** [comment]
Fair, I didn't think of that. 
I think with that I will close this issue, since the provided solutions are good enough for me.
