### ISSUE TITLE
[Question]: E2E Testing journey-maps

### ISSUE THREAD

**Issue by aram-yesildeniz** [sbb-design-systems/sbb-angular#2133]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Your Question

How to do E2E Testing?

### Give us a summary about your question

We use JourneyMaps in our app and want to create some E2E tests for the map. Since the map is just a basic HTML canvas, it's not very easy to do this straightforwardly. Do you have any tips or resources on how to write end-to-end tests for JourneyMaps? Thanks!

**Comment by besartmemeti** [comment]
Hello Aram

It will be difficult to test the canvas directly and I didn't do it myself yet. Instead we recommend testing whether the events from our Journey-Maps-Client are the way you expect them or not.

Alternatively you can test the instance of the Maplibre-Map that you can receive through our Journey-Maps-Client as well:

`@Output()
mapReady: ReplaySubject<MaplibreMap>`

There are various events that the Maplibre-Map emits. [Here](https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.MapEventType/) you can read more on that.

I hope that this answer will help you to perform the tests you want.

**Comment by aram-yesildeniz** [comment]
Cool thanks, I will give it a try with Event testing.
In the meantime we did some E2E Tests with the JourneyMaps by just simulating mouse clicks on (X,Y) Position within the viewport, which worked surprisingly well.
