### ISSUE TITLE
[Bug]: SBB Angular not working with Angular 17.1.0

### ISSUE THREAD

**Issue by U239087** [sbb-design-systems/sbb-angular#2142]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.3.0

### Operating system

Any

### Browser / Browser version

Any

### Input mode

None

### What happened?

We recently upgraded our angular dependencies to the currently newest version, 17.1.0.
After this upgrade, the sbb-sidebar component does not automatically expand the expansion-panels inside, even when they have the "expanded" property set. Also the "+"/"-" Icon do not load anymore unless you click on the expansion-panel:
<img width="310" alt="image" src="https://github.com/sbb-design-systems/sbb-angular/assets/147405637/25020ead-191a-4fb4-8596-d4743096a945">

In the above picture, I didn't touch any of the expansion-panels except for clicking on Test2.

Also in the Documentation for the sbb-sidebar, the first StackBlitz example is broken and doesn't compile: https://angular.app.sbb.ch/angular/components/sidebar/examples

### Steps to reproduce the issue

1. Upgrade project to newest Angular version and add @sbb-esta/angular to the project
2. Create a sidebar component and add some items -> as per the example in the documentation

**Comment by U239087** [comment]
Update: It seems I missed the update of the angular/cdk dependency. After updating that one, nothing works anymore. The whole project errors out like the stackblitz example I mentioned.

**Comment by mhaertwig** [comment]
Hi @U239087 
Thank you for the bug report. I can confirm that the update to Angular 17.1.0 breaks our library. We are working on a solution and provide an update as soon as possible. 

Sorry for the inconvenience. I'll keep this issue up-to-date und change the title so that everybody finds it.
