### ISSUE TITLE
Feature request: add missing icon to context menu

### ISSUE THREAD

**Issue by timschoch** [sbb-design-systems/sbb-angular#216]
**Is your feature request related to a problem? Please describe.**
The context menu component currently doesn't support icons. Based on the Design System that should be possible: https://designsystems.app.sbb.ch/de/webapps/components/contextmenu
![grafik](https://user-images.githubusercontent.com/10527318/68486789-26300600-0242-11ea-8400-41f41d53a4b6.png)

**Describe the solution you'd like**
Icons in the same color as the adjacent text. (eg selected -> red)

**Comment by kyubisation** [comment]
This is technically possible right now, but a bit complicated.
Positioning the icon should be easily possible with `display: flex` and styling the icon with `::ng-deep`.
In order to improve this #152 exists.

**Comment by jeripeierSBB** [comment]
Icons in contextmenu are supported in the meanwhile. Closed by #198
