### ISSUE TITLE
bug(textarea) remaining characters text of textarea is displayed wrong

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#217]
**Describe the bug**
The TextArea component does not show the correct text (at least in my opinion) when a max length is configured and the text was not changed by the user.

![image](https://user-images.githubusercontent.com/6132018/68597629-97b7c080-049d-11ea-9ff6-a23e98b3b0f2.png)

**To Reproduce**
1. Go to https://sbb-angular.app.sbb.ch/latest/public/components/textarea
2. Add a max length
3. See text as in screenshot above

Problem also appears when directly configuring max length in the template.

**Expected behavior**
The textarea should either not show a message if there is no text present or calculate the correct number of remaining characters.

**Additional context**
The problem is apparent in the public and business part of the library.

**Comment by davide1995** [comment]
I discovered also the following situation:
If we don't specify a maxlength we cannot write inside the textarea (delete characters works in any case)
