### ISSUE TITLE
"ERROR in Cannot read property 'members' of null"

### ISSUE THREAD

**Issue by Masterxilo** [sbb-design-systems/sbb-angular#218]
**Describe the bug**
**To Reproduce**
1. clone
2. npm install
3. ng serve

> ERROR in Cannot read property 'members' of null
ℹ ｢wdm｣: Failed to compile.

If possible, provide a reproduction with https://stackblitz.com/fork/angular-sbb -> there everything just works...

**Expected behavior**
Compilation should succeed or it should be clear what is going wrong (wrong version of something?).

**Screenshots**
![image](https://user-images.githubusercontent.com/2378665/68680672-5f2dea80-0562-11ea-900e-0283ca53b337.png)

**Desktop (please complete the following information):**
 - OS: windows, bash, wsl

**Comment by kyubisation** [comment]
This project uses the library setup from the Angular CLI: https://angular.io/guide/creating-libraries
In order to run `ng serve` you first need to build the library packages: `npm run build:libs`.
As mentioned in CONTRIBUTING, this will require more than the default amount of memory NodeJS provides. See scripts/memory.ps1 for reference.
I will try to provide a DEVELOPER.md in the near future.

**Comment by Masterxilo** [comment]
Thank you. But I cannot run 

```
.\scripts\memory.ps1
npm run build:libs
```

because `run-s` does not exist.

```
> sbb-angular@8.6.0 build:libs D:\Users\\sbb-angular
> run-s build:libs:base build:libs:components

Der Befehl "run-s" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sbb-angular@8.6.0 build:libs: `run-s build:libs:base build:libs:components`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sbb-angular@8.6.0 build:libs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\\AppData\Roaming\npm-cache\_logs\2019-11-13T09_00_52_047Z-debug.log
```

**Comment by kyubisation** [comment]
It seems as though your npm setup is broken. run-s is a command from the package npm-run-all, which should be available in an npm script.
You can try to check if node_modules/.bin contains anything. If it does not, try to run npm install or npm ci again. If it still is not available, your npm setup might be corrupt.

**Comment by Masterxilo** [comment]
You where absolutely right.

The node_modules/.bin folder was empty. repeated npm install did not repair it, neither did

```
npm install --save-dev npm-run-all
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

npm ERR! path D:\Users\E513185\OneDrive\signaletikeditor\sbb-angular\node_modules\.bin\run-s
npm ERR! code UNKNOWN
npm ERR! errno -4094
npm ERR! syscall lstat
npm ERR! UNKNOWN: unknown error, lstat 'D:\Users\E513185\OneDrive\signaletikeditor\sbb-angular\node_modules\.bin\run-s'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\E513185\AppData\Roaming\npm-cache\_logs\2019-11-13T10_24_49_026Z-debug.log
```

after I manually deleted the .bin folder finally `npm install --save-dev npm-run-all` succeeded and the .bin folder was populated.

Then I ran
```
.\scripts\memory.ps1
npm run build:libs
```
and got 
```
Built Angular Package!
 - from: D:\Users\\OneDrive\signaletikeditor\sbb-angular\projects\sbb-esta\angular-icons
 - to:   D:\Users\E513185\OneDrive\signaletikeditor\sbb-angular\dist\sbb-esta\angular-icons
------------------------------------------------------------------------------

> sbb-angular@8.6.0 build:angular-core:styles D:\Users\\OneDrive\signaletikeditor\sbb-angular
> cd ./projects/sbb-esta/angular-core/ && copyfiles "styles/**" ../../../dist/sbb-esta/angular-core/

Der Befehl "copyfiles" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sbb-angular@8.6.0 build:angular-core:styles: `cd ./projects/sbb-esta/angular-core/ && copyfiles "styles/**" ../../../dist/sbb-esta/angular-core/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sbb-angular@8.6.0 build:angular-core:styles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

so I delete .bin again and try a full npm install again, hoping this time it produces the full .bin....

**Comment by Masterxilo** [comment]
And it really seems my npm succeeds at never installing anything to .bin ...

**Comment by kyubisation** [comment]
As mentioned, maybe your npm/node installation is corrupt.
If you have eaio-ng installed, try removing nodejs entirely and installing it anew into `C:\devsbb\eaio-ng\nodejs`.

**Comment by Masterxilo** [comment]
After completely deleting package-lock.json and node_modules, npm install finally seems to have done the right thing and it has installed all the .bin tools.

Now, 
```
.\scripts\memory.ps1
npm run build:libs
```

succeeded and after that, I could do

```
ng serve
```

Very nice.

So the only real complaint/suggestion here is that it is not clear that you need to build that stuff with extra memory first...

**Comment by Masterxilo** [comment]
except... that I was presented with a completely empty page:

![image](https://user-images.githubusercontent.com/2378665/68766609-7a126480-061f-11ea-8a52-c88ceb4ac852.png)

I noticed that this happens often with the whole setup in sbb-angular/esta-cloud-angular: As soon as there is a small error somewhere, all pages of the application are completely white...

**Comment by Masterxilo** [comment]
In my experience, angular usually tries to make the unaffected components works anyways instead of failing the whole application. Or at least it displays an error message over the whole screen. Here this does not happen... It just silenty fails and I don't even see an error message in the console/terminal.

It was saying everything works:
```
ng serve --port 5999
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:5999/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 3.45 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 459 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 835 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.39 MB [initial] [rendered]
Date: 2019-11-13T13:10:35.682Z - Hash: 97f3bb742fd59d443b7f - Time: 21713ms
** Angular Live Development Server is listening on localhost:5999, open your browser on http://localhost:5999/ **
i ｢wdm｣: Compiled successfully.
```

**Comment by Masterxilo** [comment]
Oh, ok, my bad. The console states the error, I just forgot I had a filter on the console.log:
![image](https://user-images.githubusercontent.com/2378665/68767430-f6f20e00-0620-11ea-9712-44792293f7a3.png)

**Comment by kyubisation** [comment]
As mentioned I will try to add a DEVELOPER.md soonish.
For `ng serve` to display the content, you also need to run `npm run build:angular-showcase:docs` first, in order for the documentation to be built.

Also be aware, that this repository is only intended to develop the sbb angular packages. It is not meant as a starting point for projects.

**Comment by devel2ew** [comment]
Similar error when i found one error in app.modules.ts.

Check "declarations", "imports", and "entryComponents:

When i remove extra "."  in my "entryComponents" then solve the error.

entryComponents: [
    ConfirmDialogComponent,**.**
    DeviceEditComponent,
