### ISSUE TITLE
[Bug]: Angular SbbLightboxConfig closeOnNavigation not usable

### ISSUE THREAD

**Issue by cheidrich-mms** [sbb-design-systems/sbb-angular#2189]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.5.3

### Operating system

Windows 10

### Browser / Browser version

Microsoft Edge Version 121.0.2277.112 (64 Bit)

### Input mode

Mouse/Keyboard

### Additional settings

closeOnNavigation: true

### What happened?

The Lightbox offers the property 'closeOnNavigation' which leads me to the expectation, that using the browser back button should work to close a lightbox.
Unfortunately this is not the case - the browser returns to the last displayed page instead.

### Steps to reproduce the issue

Go to the Lightbox Example Page.
Open a lightbox and use the browser navigation key 'Back' to close it.
After closing a lightbox you should stay on the 'Examples' tab, but instead you are navigated to the 'Overview' tab.

**Expected behavior**

Only the lightbox is closed, the page stays the same as before.

**Comment by cheidrich-mms** [comment]
Hi Mario,

thanks for your answer.
So right now the only way to keep the Lightbox open on browser navigation is by executing the following before opening the Lightbox:
`history.pushState(null, '');`

Is there any better way to achieve this?

**Comment by mhaertwig** [comment]
I did some research yesterday and `history.pushState` in combination with `LocationStrategy.onPopState` was also the solution I found.
