### ISSUE TITLE
Bug: sbb-contextmenu is always on top

### ISSUE THREAD

**Issue by mghilardelli** [sbb-design-systems/sbb-angular#219]
**Describe the bug**
When a contextmenu is used and a lightbox is opened the contextmenu button is still visible.

**Expected behavior**
contextmenu should be invisible.

**Screenshots**
![image](https://user-images.githubusercontent.com/19152082/68953556-74a14f80-07c2-11ea-9a46-8f1608f5d0fc.png) 
![image](https://user-images.githubusercontent.com/19152082/68953604-88e54c80-07c2-11ea-9000-6f7fee052de8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version latest

**Comment by kyubisation** [comment]
This is most likely a z-index issue.
