### ISSUE TITLE
Bug: Panel from Dropdown and Select can be outside of the window

### ISSUE THREAD

**Issue by YuEmAz** [sbb-design-systems/sbb-angular#220]
**Describe the bug**
Panel from Dropdown and Select can be outside of the window

**To Reproduce**
Click on the Button/Selectbox in stackblitz
https://stackblitz.com/edit/angular-sbb-waa9qd

**Expected behavior**
If there is no space on the right side, the Panel should grow on the left side.
Or there should be a way to adjust it

**Comment by kyubisation** [comment]
The dropdown works as "expected", since the panel width exceeds the host. Since the dropdown is not a "UX approved" component, I am hesitant in extending its functionality.
The sbb-select however should not exceed the width of the host and I will check that.
