### ISSUE TITLE
[Bug]: sbb-header-environment "prod" shown in dark mode

### ISSUE THREAD

**Issue by scito** [sbb-design-systems/sbb-angular#2202]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

17.5.3

### Operating system

Win10

### Browser / Browser version

Firefox 123.0, Edge 123.0.2420.10

### Input mode

None

### Additional settings

Dark mode

### What happened?

We habe declared a stage banner in the header with
```
<sbb-header-lean
  [label]="'KK_ST_KVZ2_KORREKTUR' | translate"
  [subtitle]="('KK_ST_VERSION' | translate) + ' ' + version"
>
  <sbb-header-environment>{{stage}}</sbb-header-environment>
```
White mode:<br>
![grafik](https://github.com/sbb-design-systems/sbb-angular/assets/876593/4db6d3d7-cd74-4c84-a826-93345068edf6)

Dark mode:<br>
![grafik](https://github.com/sbb-design-systems/sbb-angular/assets/876593/0b357391-c6ea-4b97-87fd-7bd34ed6bf3d)
The [docu](https://sbb-angular.app.sbb.ch/angular/components/header-lean/overview#environment) states: 

> Note: For the production environment, the sbb-header-environment is expected to be hidden.

In white mode, no "prod" banner is shown, however in dark mode a white "prod" text without banner is shown. Nothing should be shown or written for the prod stage banner.

(A banner with text is shown for the other stages: local, dev, test and int. This is correct.)

### Steps to reproduce the issue

1. Open an page from "prod"-stage with esta-lib > 17 having a header with sbb-header-environment
2. Display in white mode -> no stage is written
3. Display in dark mode -> "prod" is written, but no stage should be written

(It is reproducible on our page https://kvz2-korrektur.app.sbb.ch/, but the page needs permissions to open it.)

**Comment by mhaertwig** [comment]
Thanks for the issue. The styling for the dark mode will be fixed in the next release which will be published next Monday.

Please note that we don't remove / show the banner dependent on the environment. It's just not visible because the text has the same color as the background and we don't style the banner if the environment is e.g. "prod". I recommend using `*ngIf` or `@if` to really remove the element from the DOM.
