### ISSUE TITLE
[Feature request]: Collapsible Bar - collapsed by default

### ISSUE THREAD

**Issue by Microtus62** [sbb-design-systems/sbb-angular#2360]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### Functionality

Hello 

We would like to use the collapsible sidebar in our project (SBB Police TPO TIME). Problem is, that the bar is by default in expanded state. That makes it impossible to use for navigation in our application, because with every page reload the bar appears in expanded state. And user has to close it manually.
Would it be possible to make it by default collapsed, or add an attribute [collapsedByDefault]="true" or something like that?

Thank in advance.
Martin Hrabos
Software Engineer at SBB

**Comment by mhaertwig** [comment]
@Microtus62, I've just released version 18.3.0. To close the sidebar by default, you can set `opened="false"` on the `<sbb-sidebar>` component.
