### ISSUE TITLE
[Question]: How to download SBB fonts

### ISSUE THREAD

**Issue by MarkPfaendler** [sbb-design-systems/sbb-angular#2379]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Your Question

How can I download SBB fonts?

### Provide as much useful information as you can

Hi, for the park & rail ad-hoc payment web app, we need access to the SBB fonts, how / where can I download them. Copy pasting the SBB header from Figma shows me I need access e.g. to "SBB Web Light" & "SF Pro Display Semibold".

**Comment by mcilurzo** [comment]
Hello @MarkPfaendler 
Here you go: https://brand.sbb.ch/document/4/de#/markenelemente/typographie-1
