### ISSUE TITLE
[Bug]: Opening the route teaser doesn't close already opened teasers

### ISSUE THREAD

**Issue by davide1995** [sbb-design-systems/sbb-angular#2404]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/sbb-angular/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/sbb-angular/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/1) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### Which version are you using

18.3.0

### Operating system

Windows 11

### Browser / Browser version

Microsoft Edge (Chromium based)

### Input mode

Mouse/Keyboard

### What happened?

We're using the package @sbb-esta/journey-maps library in order to display the Swiss map with our custom markers and custom routes.

We have configured the functionality in such a way that when a marker or route is clicked on the map, a side teaser is opened showing the information of that marker or route

The problem encountered is that if we click a marker and then a route, the teaser of the marker remains open and the teaser of the route is opened behind, forcing us to manually close the teaser of the marker.

But, if we first click on a route and then we click on a marker, the route teaser is closed and the marker teaser is shown correctly.

**Technical detail:**
In our ngOnInit component constructor we've following:

```
ngOnInit(): void {
    this.listenerOptions = {
      ROUTE: {
        watch: true,
        popup: false,
        clickTemplate: this.routeTemplate,
      },
      MARKER: {
        watch: true,
        popup: false,
      }
    }
  }
```

### Steps to reproduce the issue

Described in the "What happened" section

**Comment by davide1995** [comment]
Do you have any update on this?

**Comment by mstankala** [comment]
Hi @davide1995,

Thank you! 
We have created a bug in our Bugboard for the issue you noted in the journey-maps (ref. ROKAS-2263).
Our team will investigate this as soon as possible and work on providing a fix. 
We appreciate your patience and will keep you updated on our progress.

Best regards,
Marek

**Comment by andrinsibold** [comment]
Hi @davide1995 
Thank you for reporting this bug. It has been fixed and merged.

Best regards,
Andrin
