### ISSUE TITLE
Bug: Broken Perfect Scrollbar on Checkbox click inside Accordion

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#243]
**Describe the bug**
When using checkboxes (and radios?) in a accordion that is in a perfect scrollbar, in certain situations the scrollbar content is "shiftet" a little out of view - see gif:

![crazy-scroll](https://user-images.githubusercontent.com/117919/70157311-a288fe00-16b5-11ea-85e5-f2a33bc33f83.gif)

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-broken-perfect-scrollbar-on-checkbox
2. Click on the second checkbox (test label2)
3. Observe that the accordion has some negative offset to its container (the red border)

**Expected behavior**
The container should not be moved.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome (not reproducable with FF?)
 - Version 78.0.3904.108

**Comment by kyubisation** [comment]
I have also noticed problems with the perfect-scrollbar. I'm currently considering switching to native scrollbars for large areas, since scrollbar styling is now available for most modern browsers: https://css-tricks.com/the-current-state-of-styling-scrollbars/#article-header-id-0
