### ISSUE TITLE
Bug: Input field in disabled mode does not work together with id-attribute

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/sbb-angular#246]
**Describe the bug**
Field component in angular-public does not work in state disabled. It seams like the problem only occures if I set a custom id in combination with formControlName.
Even on the demo page it does not work.
https://sbb-angular.app.sbb.ch/latest/public/components/field

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-6sr1oi

**Expected behavior**
Input field should be disabled

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 78.0.3904.108

**Comment by kyubisation** [comment]
Since Angular 8 (I believe) Reactive Forms no longer work with the disabled attribute. A control can be disabled by using the .disable() method on FormControl.

See https://stackblitz.com/edit/angular-sbb-9vizzk?file=src/app/app.component.ts
