### ISSUE TITLE
Bug: Utilization icons don't have the same sizes

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#254]
**Describe the bug**
Since you are working anyway on a new icon generation procedure: The utilization icons don't have the same sizes when using size="fixed".

![image](https://user-images.githubusercontent.com/6132018/72238951-a460ae00-35df-11ea-99cc-071cc2aa8349.png)

**To Reproduce**
1. Use utilization icons and set size to fixed
2. Per default medium has another size than the other icons

See also https://stackblitz.com/edit/angular-sbb-zm8yyp.

**Expected behavior**
All four icons have the same size when fixed.

**Comment by kyubisation** [comment]
This should be fixed with the new icons, but I will check to make sure.
