### ISSUE TITLE
Bug: sbb-header with sbb-usermenu do not work together

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/sbb-angular#269]
**Describe the bug**
When using both the HeaderModule of angular-business and the UserMenuModule of angular-public (to have a nice header) an error 'More than one component matched on this element (DropdownComponent,DropdownComponent)' occurs. 

Ps. I use the version 8.7.11 with sbb-angular version 8.3.3 it works...

**To Reproduce**
https://stackblitz.com/edit/angular-sbb-an5hj6

**Expected behavior**
No error ;) 

**Desktop:**
 - OS: Windows
 - Browser chrome
 - Version 79.0.3945.130

**Comment by kyubisation** [comment]
The reason is both the header and usermenu export the dropdown module. In order to work around this, use the usermenu module of business.
Since removing the exported modules is a breaking change, we will definitely fix this with the Angular 9 release.

**Comment by luecu** [comment]
Thanks for the fast response.  I didn't find the UserMenuModule in angular-business before because it is located under /usermenu (shame on me)...
Now it works find, thanks a lot!

**Comment by kyubisation** [comment]
No problem 😃 
I will leave this issue open, so we can close it, when we fix it for Angular 9 release.
