### ISSUE TITLE
Bug: sbb-checkbox-panel overflow problem

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#274]
**Describe the bug**
If you usea sbb-checkbox-panel with a long label or subtitle, the text visually overflows its corresponding panel.

**To Reproduce**
1. Go to https://angular.app.sbb.ch/latest/icons/experimental
2. Make window small
4. See situation like in screenshot below

**Expected behavior**
panel should ajust its size to content

**Screenshots**
![image](https://user-images.githubusercontent.com/29278232/73753478-12be0980-4763-11ea-8179-b8f07c0a7d28.png)

**Desktop:**
 - OS: windows, chrome

**Comment by kyubisation** [comment]
As discussed, we will define an overflow limitation.
