### ISSUE TITLE
Feature request: Provide examples for pagination, filtering and sorting with DataSource

### ISSUE THREAD

**Issue by livia-e** [sbb-design-systems/sbb-angular#339]
**Describe the solution you'd like**
I would like to use the table component with the following features: 
- pagination
- selection of rows
- filter by fields and filter by multiple fields
- search in columns

Are there any plans for adding these features?

**Comment by kyubisation** [comment]
These features are directly or indirectly available via https://angular.app.sbb.ch/latest/business/components/table
Is there something that you are missing? Or would you like additional examples?

**Comment by livia-e** [comment]
Thank you for the quick answer. I only saw grouping and sorting as special feature for table. Yes maybe some additional examples would be nice. Thank you.

**Comment by kyubisation** [comment]
By implementing your own DataSource you can filter, sort and paginate as you desire.
However, I understand that without the appropriate examples this is difficult to do.
We will try to provide additional examples.

**Comment by livia-e** [comment]
Can you please give a rough estimation when can we have additional examples available. Thank you in advance.

**Comment by kyubisation** [comment]
If everything goes well at the end of april.

**Comment by jeripeierSBB** [comment]
Closed by #379
