### ISSUE TITLE
Bug: UserMenu displays incorrectly in IE11

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#341]
**Describe the bug**
A collapsed UserMenu component displays username incorrectly in IE11. You can check it using the UserMenu showcase [page](https://angular.app.sbb.ch/latest/business/components/usermenu).

**Screenshots**
![sbb-um-issue](https://user-images.githubusercontent.com/45698825/76531158-d8dcd300-6485-11ea-8ed0-59570df29f1c.png)

**Expected result**
the full user name is displayed in collapsed mode

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser IE11

**Comment by kyubisation** [comment]
Thank you for bringing this to our attention. We will have a look at this.
