### ISSUE TITLE
Feature request: Autocomplete component should support debounce operator

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#342]
**Is your feature request related to a problem? Please describe.**
To improve searching performance only emit an item from an Observable if a particular timespan has passed without it emitting another item (for more info take a look at the Rx [Debounce](http://reactivex.io/documentation/operators/debounce.html) operator)

**Describe the solution you'd like**
Integrate Rx debounce filtering operator

**Comment by kyubisation** [comment]
This is already possible.
It is entirely up to you how you populate the autocomplete options.

```ts
this.options = this.autocompleteFormControl.valueChanges.pipe(
  debounceTime(300),
  switchMap(v => this.backendService.getOptions(v))
);
```

```html
<input [sbbAutocomplete]="ref">

<sbb-autocomplete #ref>
  <sbb-option *ngFor="let option of options | async" [value]="option.value">{{ option.label }}</sbb-option>
</sbb-autocomplete>
```

**Comment by sonatdev** [comment]
I got it, thanks!
