### ISSUE TITLE
Feature request: Notifications should disappear after specified timeout

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#343]
**Is your feature request related to a problem? Please describe.**
To save space on the screen notifications should disappear after specified timeout

**Describe the solution you'd like**
for more info please take a look at the [angular-notifier](https://www.npmjs.com/package/angular-notifier) library

**Comment by kyubisation** [comment]
This is not intended for the non-toast variant: https://digital.sbb.ch/en/webapps/components/notification
If you are talking about the toast variant, see #315

**Comment by jeripeierSBB** [comment]
Hi @sonatdev, is it ok for you if we close this issue?
