### ISSUE TITLE
Bug: odd zooming behaviour

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#348]
**Describe the bug**
When zooming in browser some components behave odd. The Occurence of an odd zoom behavior depends on screen resolution and viewport.

**To Reproduce**
1. Go to https://sbb-angular.app.sbb.ch/latest/public/components/accordion
2. Zoom in or out until the components size is odd

**Screenshots**
![Zoom_bug](https://user-images.githubusercontent.com/50302840/77297596-cfefcb00-6ce9-11ea-99d9-675440330669.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox..
 - Screen Resolution: 2560 x 1440

**Comment by kyubisation** [comment]
That's really odd. At a guess I'd say this is related to media queries.
We will investigate this.

**Comment by kyubisation** [comment]
We analyzed this and realized it is an edge case and working as intended, while not being intuitive.
The media breakpoint is at 2561px, so when zooming out on your screen resolution, the 4k styling is applied, which makes everything bigger.
This would also happen on 1980 screen resolutions at 75% zoom.
