### ISSUE TITLE
Bug: Usermenu click on arrow

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#349]
**Describe the bug**
We received Feedback from several clients that the Usermenu doesn't work properly. By clicking directly on the arrow the usermenu doesn't close or open whereas clicking on other parts of the usermenu works fine.

**To Reproduce**
1. Go to https://sbb-angular.app.sbb.ch/latest/public/components/usermenu
2. Click on arrow in usermenu

**Expected behavior**
By clicking on arrow the usermenu should close or open.

**Screenshots**
![usermenu_bug](https://user-images.githubusercontent.com/50302840/77299094-44c40480-6cec-11ea-8819-13bae9010814.gif)

**Comment by jeripeierSBB** [comment]
@zer0p1 Fix ist mit Version 9.2.0 releast.
