### ISSUE TITLE
Feature request: Leaflet Map

### ISSUE THREAD

**Issue by ajoos** [sbb-design-systems/sbb-angular#359]
The ArcGIS driven map components are very feature rich and provide a tight integration with the SBB G# GIS stack. Sometimes, however, that is not needed and a light weight, fast map componenten would be a prefered solution in an app. 

For cases like these, angular-maps should be extended by a *Leaflet-based map component* providing basic mapping functionalities. Esri (ArcGIS) map services should be usable as well (trough the Esri Leaflet components, see Github). 

Advantages of such a component would be: The leaflet component initialized in 100ms, while the ArcGIS API takes almost 1s. Might not be relevant in many cases, but sometimes it is. Leaflet has additional symbolization for Clustering that is already a need in some projects. 

Once the component is defined and available, we'll need to be able to provide a good checklist on when to use and when the ArcGIS map would be the wiser choice.

**Comment by kyubisation** [comment]
To give a comment on this; I think this is a good idea. However due to the nature of node package managers, it might be better to create a separate package for this (e.g. @sbb-esta/angular-maps-leaflet or @sbb-esta/angular-leaflet).

**Comment by ajoos** [comment]
We have been discussing the exact same question just this morning. Possibliy @WyssTobi already discussed it with you afterwards? Adding another package feels like polluting sbb-esta a bit. Are there any other options (like having a deploy task that removes all dependecies that are not actually needed, for example kicking out Leaflet if only the Esri maps are used or vice versa)?

**Comment by kyubisation** [comment]
No, I have not yet heard from him. I just checked the issues again, in case I missed something, since I was quite busy the last few days.
This is not a problem for building an app with this library, as code that is not imported will be removed during tree-shaking.
It is more a problem of having to download both dependencies to esri and leaflet during installation of the package. This is not a huge problem, but feels like cluttering the package dependencies with unneeded space and download bandwidth (even if it is fairly small in comparison with other things), because I assume no consumer will use both in the same project.
I personally do not have a problem with adding an additional package, as it means we provide clear-cut packages that provide exaclty what is needed.

Please wait a bit if you want to start implementing this soon, as I am currently busy with refactoring our build system, which I want to merge this week.

**Comment by ajoos** [comment]
We have been discussing this again and think it would still make more sense to include Leaflet and ArcGIS API for Javascript mapping components in the same (and a single) package. We expect unused code to be removed during tree shaking (as you said).

The Leaftlet part weights only a few kilobytes. The ArcGIS API in turn is large and fat and that's where your argument would be valid (then again, compared to other packages and what people download every day it's not relevant either).

However we emphasize on the arguments for a single package:

1) One stop package for 2d/3d map displaying/mapping in sbb-angular (only a subset of users actually requires the map package, and we believe it makes sense to them to have all options availabe at once). The ArcGIS map components are a key component to work with the full power of the G-SHARP platform and thus stay the "main" components in the package.

2) Have a single package allows us to have a single documentation entry where we discuss pros and cons of the different way of displaying maps (Leaftleft, 2D ArcGIS, 3D, ...). No documentation clutter or duplication.

3) We presume to be using Esri (ArcGIS) types within the Leaflet mapping component as well (to be able to use ArcGIS/G# services within Leaflet maps), our implementation of Leaflet would not be able to live completely standalone (-> tree shaking removes the overhead in any case). 

@kyubisation after all it's you to decide on how sbb-angular should be built and what makes sense on the level of package sepraration. Let's discuss all arguments once you're available again.

**Comment by WyssTobi** [comment]
After a discusstion today with @kyubisation we decided to split esri-maps and leaflet-maps in to seperate packages. Following, the reasons:
1. With angular.app.sbb.ch we have a central entrypoint and we are able to add a quick description to each package.
2. We don't want to bloat the package up, rather we want to keep everything clean and thin.
