### ISSUE TITLE
Feature request: automatically set sbb-header environment ribbon color 

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/sbb-angular#361]
**Is your feature request related to a problem? Please describe.**
in the sbb-header the environment ribbon showes the current environment the user is working on, indicated by a label and color. According to the sbb design system the color to use for each environment is defined: https://digital.sbb.ch/de/webapps/modules/header

Today each project has to do the mapping between environment and color by their own.

**Describe the solution you'd like**
It would be cool if i just can give the current environment to the sbb-header component (maybe as Enum?) and the correct color is then automatically set based on the given environment.

**Additional context**
https://digital.sbb.ch/de/webapps/modules/header

**Comment by kyubisation** [comment]
This was considered and discarded, due to the many different environments out there. However, we could provide default coloring for the defined environments.
