### ISSUE TITLE
Feature request: Provide Template for Business Bugs

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#362]
This is very low prio, but something that sometimes would be useful for me =D.

Currently when creating a bug report it is recommended to provide StackBlitz example of the problem. This is useful also for testing out quick features are trying to reproduce small issues / examples for other users. However only the public library is included and used, when switching the dependencies to business, the tool takes a lot of time.

Of course I could create a template just for myself, however, I think this could useful for everybody.

*Desired change*
- Bug template also contains another link to StackBlitz which can be used for the business part of the library

**Comment by kyubisation** [comment]
That is quite reasonable. Since this should be a minor change, I will try to provide this soonish.
