### ISSUE TITLE
Bug: sbb-pagination should be usable with sbbTable

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#363]
**Is your feature request related to a problem? Please describe.**
Currently I think it is not possible to use the [Pagination ](https://sbb-angular.app.sbb.ch/latest/business/components/pagination) component together with the SBB [table](https://sbb-angular.app.sbb.ch/latest/business/components/table). At least I am not able to make it work (see [here](https://stackblitz.com/edit/angular-sbb-9qmmpk?file=src%2Fapp%2Fapp.component.ts)).

**Describe the solution you'd like**
The SBB pagination component can be assigned to a data source and it works as expected (e.g. like in [Material](https://material.angular.io/components/table/overview#pagination)).

**Comment by kyubisation** [comment]
Sorry, this is an oversight on my part.
I will try to fix this as soon as possible.

**Comment by kyubisation** [comment]
The SbbTableDataSource expects a .page and .initialized Observable on the PaginationComponent. These need to be implemented (or aliased).
Maybe also compare with the Paginator implementation of Material.
