### ISSUE TITLE
Bug: Frameless Button with Icon changes size on hover

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#369]
**Describe the bug**
When using the button in mode frameless with an icon, on hover the size changes, which gives funny behavior:
![frameless-button](https://user-images.githubusercontent.com/117919/79762752-70560100-8323-11ea-85fa-7baf490b8c80.gif)

**To Reproduce**
```
                <button sbbButton mode="frameless">
                  <sbb-icon-arrow-right *sbbIcon></sbb-icon-arrow-right>
                  <span>Alle Empfänger entfernen</span>
                </button>

```

**Expected behavior**
Animation should not change size.

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version 9.4.0

**Comment by jeripeierSBB** [comment]
@daniel-sc thank for the report. How did you use the tooltip? in public or business as component or in business as directive?

**Comment by daniel-sc** [comment]
@jeripeierSBB I used the tooltip module from the business module as a component:
```html
            <sbb-tooltip class="location-menu" #tooltip>
              <sbb-icon-context-menu *sbbIcon></sbb-icon-context-menu>
              <div class="location-menu-content">
                <button sbbButton mode="frameless" (click)="deleteAll(null, null); tooltip.close(true)">
                  <sbb-icon-arrow-right *sbbIcon></sbb-icon-arrow-right>
                  <span>Alle Empfänger entfernen</span>
                </button>
              </div>
            </sbb-tooltip>
```
