### ISSUE TITLE
Feature request: Autocomplete component should support Tab key press events

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#371]
**Is your feature request related to a problem? Please describe.**
To improve user usability of the autocomplete component Tab key press should be supported (onle Enter key press events are supported for now). It'll allow to select value and move to the next component using only one user action.

**Comment by jeripeierSBB** [comment]
After careful consideration we consider this behavior not standard practice for autocompletes. 
Please reopen this issue if you have an argument for why you consider this the correct way of implementing this.
