### ISSUE TITLE
Feature request: Easily display array of points/coordinates on maps

### ISSUE THREAD

**Issue by ajoos** [sbb-design-systems/sbb-angular#373]
A simple but often used and require task related to mapping and displaying of data on a map is: Show a list of points/coordinates on a map (at their correct location, with some basemap in the background, with a default symbolization). This should be a straight forward functionality of every map component in sbb-angular.

The functionality should:
* Allow an array of points/coordinates (in a matching coordination system, for example WGS84 or LV95) to be added to or processed by the map component with no more than a few intuitive lines of code
* Display a simple symbol (f.e. a red circle) at the supplied coordinates, a simple symbol 
* Work similar with the Leaflet map as well as with the Esri 2D map. For the Esri 3D map/scene the point array must a) either supply a Z-value (height in space) or b) the points need to be displayed "on top" of the terrain model of the 3D scene (that should be a default option of the renderer in the SceneView).

**Comment by jeripeierSBB** [comment]
@ajoos Is this still relevant or can we close this issue?

**Comment by ajoos** [comment]
It is still a requirement, but can be closed here since we will adress this by other means.
