### ISSUE TITLE
Bug: Processflow steps not acessible on overflow in IE

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#382]
If to many Processflow steps are displyed the overflow is hidden and accesible by horizontal scrolling inside Processflow component:

![processflow_overflow](https://user-images.githubusercontent.com/50302840/80516581-f73e5580-8983-11ea-8161-900c5f3cba77.gif)

In IE the processflow steps are cutted until it fits on view port. (Scrollbar probably not supported in IE?):

![process_overflow_ie](https://user-images.githubusercontent.com/50302840/80516747-3a002d80-8984-11ea-9bc4-ff179c96efdd.PNG)

**To Reproduce**
1. Create a Processflow component with many steps until an overflow occurs
4. Compare behavior between Chrome (or Firefox) and IE

If possible, provide a reproduction: https://stackblitz.com/edit/angular-sbb-jnz8bd 

**Desktop (please complete the following information):**
 - OS: all
 - Browser Chrome, Firefox, Edge, Internet Explorer
 - Version 9.4.0

**Comment by kyubisation** [comment]
This is probably a flex issue. We will have a look at this.

**Comment by zer0p1** [comment]
the fix with `flex: 1 0 auto` statement causes an unsightly issue (see: screenshot). 
![prcessflow_padding](https://user-images.githubusercontent.com/50302840/81070864-2739ab80-8ee4-11ea-8892-1f8f2491961b.PNG)

**Comment by kyubisation** [comment]
Sorry about that. I should have checked better. I will try to fix this as soon as possible.
