### ISSUE TITLE
Bug: Dropdown not dismissing clicking another window object

### ISSUE THREAD

**Issue by davide1995** [sbb-design-systems/sbb-angular#384]
**Describe the bug**
If the dropdown element is opened and we click on another window object of the page (e. g. an iframe), the dropdown will not be dismissed

**To Reproduce**
1. Go to https://stackblitz.com/edit/sbb-dropdown-focus
2. Click on the "Choose language" button
3. Click on the white space inside the square (it's an about:blank iframe)
5. Click now outside the white square
6. The dropdown is dismissed

**Expected behavior**
The dropdown should be dismissed clicking inside the white square. The button already loose the focus (right)

**Desktop**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 81

**Comment by kyubisation** [comment]
This might simply be a limit when dealing with iframes. We will investigate this, but I'm not certain that we can fix this.

**Comment by davide1995** [comment]
Hello. I see there is a PR about this problem but not yet merged since May. Is there any update about that?

**Comment by jeripeierSBB** [comment]
Hi Davide, Sorry for not updating you on this issue. We found a possible solution, but it's not reliable yet and we decided to postpone this task. At the end of the next week, I will discuss this issue with @kyubisation.

**Comment by davide1995** [comment]
Hi @jeripeierSBB, thanks for the info

**Comment by jeripeierSBB** [comment]
This bug was resolved with release 13.0.0 which replaces `sbb-dropdown` with the new `sbb-menu`.
