### ISSUE TITLE
Bug: tooltip box missing

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#390]
**Describe the bug**
For Tooltips on hover wich are used as directive, the tooltip box is missing. However, the tooltip example on https://sbb-angular.app.sbb.ch/latest/business/components/tooltip works fine. 

![tooltip-hover-demo](https://user-images.githubusercontent.com/50302840/81146961-9ad9c800-8f79-11ea-983b-2ea723e0adc7.PNG)

But when implemented manually on any element the tooltip box strangely always is missing.

![tooltip_bug](https://user-images.githubusercontent.com/50302840/81146716-1be48f80-8f79-11ea-9e7c-d23810f94494.gif)

See: https://stackblitz.com/edit/angular-sbb-jnz8bd 

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-jnz8bd 
2. Try "Test Tooltip" which is implemented on a span element

**Expected behavior**
Tooltip should always be boxed like the example on https://sbb-angular.app.sbb.ch/latest/business/components/tooltip 

**Desktop (please complete the following information):**
 - OS: all
 - Browser all

**Comment by jeripeierSBB** [comment]
Hi @zer0p1, thank you very much, we have already fixed it. With the next release (in the next days) you have access to the correctly styled tooltip directive.
