### ISSUE TITLE
Bug: overflow-x on processflow breaks sticky elements

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#399]
**Describe the bug**
The css `overflow-x` on `sbb-processflow` prevents elements within to be positioned with `position: sticky` - see https://stackoverflow.com/a/58295375/2544163

**Expected behavior**
It should be possible to position position elements "sticky" wihtin the processflow component.

**Comment by kyubisation** [comment]
I'm not quite sure what you mean. Should only one step be sticky? What browser is affected?

**Comment by daniel-sc** [comment]
Hi @kyubisation 

I prepared a stackblitz for reproduction: https://stackblitz.com/edit/angular-sbb-bnpdnq (remove the `overflow-x` to see wrong behavior).
This happens at least in current Chrome on WIN.
