### ISSUE TITLE
Bug: Impossible to import colors.scss

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#406]
**Describe the bug**
It's impossible to import `colors.scss` to reuse colors definitions since version 9.4.1.
In the 9.4.0 version it worked fine: `@import "~@sbb-esta/angular-core/styles/common/colors";`
The `styles` directory isn't generated after the `ng build` command execution.

Is it expected behavior?

**Comment by kyubisation** [comment]
I apologize, I forgot that these were part of the public api. We will fix this as soon as possible.

**Comment by sonatdev** [comment]
@kyubisation, thanks!

**Comment by kyubisation** [comment]
As a workaround you can import from `~@sbb-esta/angular-public/styles` or `~@sbb-esta/angular-business/styles`
