### ISSUE TITLE
Feature request: TreeTable component

### ISSUE THREAD

**Issue by sonatdev** [sbb-design-systems/sbb-angular#419]
**Is your feature request related to a problem? Please describe.**
To display hierarchical data in tabular format tree table should be used. To show/hide children nodes rows could be expanded/collapsed.

Example of table data:
```
{
  "data": [
    {
      "data": {
        "prop_1": "value_1",
        "prop_2": "value_2",
        "prop_3": "value_3"
      },
      "children": [
        {
          "data": {
            "prop_1": "child_value_1_1",
            "prop_2": "child_value_1_2",
            "prop_3": "child_value_1_3"
          }
        },
        {
          "data": {
            "prop_1": "child_value_2_1",
            "prop_2": "child_value_2_2",
            "prop_3": "child_value_2_3"
          }
        }
      ]
    }
  ]
}

**Comment by kyubisation** [comment]
Do you mean something similar to https://material.angular.io/components/tree/overview?

**Comment by sonatdev** [comment]
something like this, but it should be implemented as a table

more accurate example can be found [here](https://www.primefaces.org/primeng/showcase/#/treetable)

**Comment by mhaertwig** [comment]
A while ago we've added an example of an expandable table: https://angular.app.sbb.ch/angular/components/table/examples
This should solve the issue. If not, please reopen this issue.
