### ISSUE TITLE
Bug: sbb-select dropdown position is wrong if select-container moves

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/sbb-angular#423]
**Describe the bug**
When I open a sbb-select component and then select-container is moved because of gui reordering, the dropdown list stays at the origin position and is not attached to the container anymore.. See video..
[Bildschirmvideo aufnehmen 2020-05-19 um 14.45.53.zip](https://github.com/sbb-design-systems/sbb-angular/files/4650594/Bildschirmvideo.aufnehmen.2020-05-19.um.14.45.53.zip)

**To Reproduce**
1. open https://sbb-angular.app.sbb.ch/business/components/select 
2. open Examples
3. open a dropdown list
4. change screen size

**Comment by kyubisation** [comment]
This can probably be solved by correctly configuring the overlay API.
