### ISSUE TITLE
Bug: Styling Checkbox Panel 

### ISSUE THREAD

**Issue by mghilardelli** [sbb-design-systems/sbb-angular#433]
**Describe the bug**
After updating to 9.6.0 the vertical alignment of Checkbox Panel is broken. 

**Screenshots**
![image](https://user-images.githubusercontent.com/19152082/82872950-0f2dd880-9f34-11ea-8d0d-0642cb2f1056.png)
![image](https://user-images.githubusercontent.com/19152082/82873049-35ec0f00-9f34-11ea-98f3-dda2e19f54ba.png)

**Comment by jeripeierSBB** [comment]
Probably caused by #413
