### ISSUE TITLE
Bug: Property filter in sbb-table always includes empty cells

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/sbb-angular#445]
**Describe the bug**
If I have a table with three entries e.g. "hans", null, "peter" and then add a property filter on this column and select "hans", the null row still remains in the table

**To Reproduce**
1. Add a property-filter on a column containing null rows
2. activate the property-filter with any value
3. the null entries remain visible in the table

[Bildschirmvideo aufnehmen 2020-06-02 um 08.41.33.zip](https://github.com/sbb-design-systems/sbb-angular/files/4715263/Bildschirmvideo.aufnehmen.2020-06-02.um.08.41.33.zip)

**Comment by luecu** [comment]
Change table-data-source.ts line 417 to ".filter((key) => typeof tableData[key] !== 'undefined')" fixes the problem

**Comment by kyubisation** [comment]
This is not necessarily a bug, since null-handling is not standardized.
However, I think we should carefully consider this.
I will discuss this next week with @jeripeierSBB.
