### ISSUE TITLE
Bug: Message "Property checked is not provided by any applicable directives nor by sbb-checkbox element" in IDE

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#446]
**Describe the bug**
When using a more recent version of the @sbb-esta/angular-business library, I see the following error messages:

![image](https://user-images.githubusercontent.com/6132018/83602597-26dc1100-a573-11ea-9447-0e84c2fa96ee.png)

Everything works as expected, but the IntelliJ IDE does complain. Does this work in VS Code?

I assume this might be, because the metadate is not correctly recognized, when extending components. Therefore maybe related:
- https://github.com/angular/angular/issues/25249

**Comment by kyubisation** [comment]
That's strange. We implement the @Input() setter coercion, as specified here: https://angular.io/guide/template-typecheck#input-setter-coercion
The linked angular issue should not affect us, as we are now using bazel.
Could you enable `strictTemplates` in the `angularCompilerOptions` section of you tsconfig.json file and try again? I wonder if it is an Angular compiler problem or only an IntelliJ problem. (VS Code does not complain, as far as I can tell.)

**Comment by kyubisation** [comment]
Related: https://youtrack.jetbrains.com/issue/WEB-40709?_ga=2.225162653.625925371.1591168510-1076872957.1591168510

**Comment by efux** [comment]
Adding `strictTemplates` yields no error related to the sbb-checkbox (although some other errors). So I guess this is more likely an IntelliJ issue (I am using 2020.1). If that is the case, do not waste too much time on this. It works just fine and I know it has no impact, but might confuse other developers. What is strange, is, that if I open projects where I use version ~9.0.0 of the library, IntelliJ does not complain.

Does Bazel alter how the compiled outputs look like? Especially when for the compiled output library Ivy is disabled?

**Comment by kyubisation** [comment]
While there are certainly some differences (as the code is now processed with tsickle), the changes in the metadata are marginal.
I don't know how IntelliJ interprets the data from the libraries, so I think the linked issue to the JetBrains bug tracker is the only solution.

**Comment by efux** [comment]
My issue was solved by removing node_modules / package-lock.json / Invalidating all caches / npm install and reloading everything from disk. Somehow an update has not been well processed by IntelliJ.
