### ISSUE TITLE
Feature request: Table filtering of complex objects (flattening)

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#447]
**Is your feature request related to a problem? Please describe.**
I am trying to filter a table with a string. The global filter applied by the SbbDataSource converts all keys of an object to a string, in which it then searches for the filter string. 

```javascript
const data = {a: 'A', b: 'B', complex: {z: 'C'}};

// similar to  _reduceObjectToString method in table-data-source.ts
Object.keys(data).reduce((currentTerm, key) => {
      return currentTerm + (data)[key] + '◬';
    }, '');
```

This method call returns `A◬B◬[object Object]◬`. So if I search for `C` the element will not match.

**Describe the solution you'd like**
I would expect it to recursively reduce all other objects to strings as well, e.g.
`A◬B◬C◬`

**Alternatives**
Or would it be expected (=best practice, especially performance-wise?), that i flatten the object myself prior to applying it as DataSource?

**Comment by kyubisation** [comment]
Personally I think we're already stretching it performance-wise with our property filtering implementation. It would probably be better if you could flatten the objects before passing them into the DataSource.
We can leave this issue open to see if it garners more interest by other consumers.

**Comment by jeripeierSBB** [comment]
Can be implemented with a custom data source. We will close this for now.
