### ISSUE TITLE
Feature Request: Lazy rendering tabs

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#456]
**Maybe this is rather a feature request than a bug.**

**Describe the bug**
sbb-tabs component somehow initializes the component of a tab even though the tab content does not have to be rendered.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-vuyz1p
2. Open Console
3. OnInit lifecycle of both components has been called

However, when you check the DOM, the element app-def is not there at all. When switching between tabs, the component is only initialized once.

**Expected behavior**
OnInit method of component is only called, when the component has to be rendered. In this case this should happen, when I switch the tab.

The expected behaviour would be similar to the GhiComponent in the example. The OnInit method is called every time the state is toggled.

The default Material tabs component behaves the same way, however, there we can use the matTabContent directive for this behaviour. See https://stackblitz.com/edit/angular-9-material-starter-fuuu1a.

**Additional context**
This affects business and public.

**Comment by kyubisation** [comment]
In my opinion, this is not a bug, but simply a limitation of our current implementation. 
I changed this to a feature request.
We would appreciate a PR, if you urgently need this.
