### ISSUE TITLE
Bug: fix(dialog): close on backdrop click

### ISSUE THREAD

**Issue by efux** [sbb-design-systems/sbb-angular#464]
**Describe the bug**
Currently it is not possible to close a SBB dialog from business by clicking on the backdrop. Documentation does not specify how this behaviour could be achieved.

Is there someway to access the OverlayRef from CDK and then listening to the event myself?

**Expected behavior**
If disableClose is set to false (default setting), the dialog should click both on Escape and clicking on the backdrop.

**Comment by kyubisation** [comment]
Not currently intended by https://digital.sbb.ch/de/webapps/modules/dialog
@Frenggi What is your opinion on this?

**Comment by Frenggi** [comment]
As discussed, we will provide the possibility for closing the dialog by clicking the backdrop.
