### ISSUE TITLE
Bug: Icon Schematics broken

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#465]
**Describe the bug**
When running the command `ng generate @sbb-esta/angular-icons:svg-registry --help` (or any other schematics command for icons) the following error occurs:
```
An unhandled exception occurred: Cannot find module 'C:\devsbb\projekte\PROJECT\node_modules\@sbb-esta\angular-icons\schematics\svg-registry\index'
See "C:\Users\USER\AppData\Local\Temp\ng-03gjFe\angular-errors.log" for further details.

```

**To Reproduce**
see above

**Expected behavior**
Command should work

**Desktop (please complete the following information):**
 - OS: Win (SBB-Standard)
 - Browser n/a
 - Version SACL 9.7.1

**Additional context**
A manual workaround is to copy the folders `node_modules/@sbb-esta/angular-icons/schematics/ng-generate/svg-icons` to `node_modules/@sbb-esta/angular-icons/schematics/svg-icons` (and analogou for `svg-registry`).

**Comment by kyubisation** [comment]
Closed by #484
