### ISSUE TITLE
Bug: button issues (moving text / too long labels)

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#500]
**Describe the bug**
- button text moves when switching disabled and primary/secondary state
- If entering long texts and using icons, the right icon is not displayed anymore or wrong displayed.

**To Reproduce**
'https://angular.app.sbb.ch/public/components/button'

**Additional context**
- By adding a an invisible border to the primary and secondary border, it is possible to prevent text moving when disabling
- By adding an additional span to the button label, it's possible to solve the long text issue

**Comment by kyubisation** [comment]
Closed via #745
