### ISSUE TITLE
Bug: no possibility to show long texts in select/options if text has ellipsis

### ISSUE THREAD

**Issue by dfsbb** [sbb-design-systems/sbb-angular#567]
**Describe the bug**
select component for **business** and **public** library: when content of select-options are bigger than the defined size of the select component, the text will be shown with ellipsis (...). It would be great, if the user could see the whole text if he hovers over the option item.

**Expected behavior**
whole text will be shown, if the user hovers over the text item with ellipsis. This behaviour should apply to the context (option-items) as well as to the input field itself 

**Screenshots**
<img width="271" alt="Bildschirmfoto 2020-08-04 um 14 07 48" src="https://user-images.githubusercontent.com/45092436/89292737-20464480-d65d-11ea-8b6e-5ffc2874288f.png">

**Comment by kyubisation** [comment]
I'm not quite sure I understand the expectation on what exactly should happen?
If you want simple hover functionality you can do this with the `title` attribute.
If you want something more complex I do not know what and worry that it would either break the select or introduce massive complexity.

**Comment by dfsbb** [comment]
@kyubisation you're absolutely right. think we could solve it with the title attribute. should I close the bug directly?

**Comment by kyubisation** [comment]
I'm relieved, if the title attribute is enough for your use case. 😃 
I will close the issue. Feel free to reach out again if you there is another issue.
