### ISSUE TITLE
Feature request: sbb-tabs working with angular router

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#568]
It would be great, if the tabs component can be used as navigation with a router-outlet for the content. See https://material.angular.io/components/tabs/overview#tabs-and-navigation for the material way to provide the solution.

**Comment by YuEmAz** [comment]
thum up


I could use it too

**Comment by jeripeierSBB** [comment]
> thum up
> 
> I could use it too

Should be available with next major release, probably around autumn.
