### ISSUE TITLE
Bug: Sbb-error wrongly takes over event

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#573]
Sbb-error wrongly takes over an event when a input field lost his focus. 
This gives the impression that the following event didn't work e.g. a button click. The Button has to be clicked twice as the sbb-error takes over the first click event. 

Sbb-error should not override other events

![sbb_errror_event](https://user-images.githubusercontent.com/50302840/89882581-4fae0180-dbc7-11ea-9a8f-79e8eac31e03.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: all

**Comment by kyubisation** [comment]
This is probably related to the displacement of the button due to the error.
We could reserve space below the input, but that would be a breaking change.
We will investigate options.

**Comment by zer0p1** [comment]
Updating the library to current Version 10 fixed the issue.
