### ISSUE TITLE
Bug: Fullscreen loading indicator does not cover sidebar and header

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#602]
**Describe the bug**
If using `<sbb-loading mode="fullscreen"></sbb-loading>` the backdrop does not cover the sidebar and the header.

**To Reproduce**
1. Go to 'https://angular.app.sbb.ch/public/components/loading'
2. Click on 'Activate Fullscreen Spinner'
3. See that overlay does not cover header and sidebar

**Expected behavior**
Fullscreen loading indicator should cover sidebar and header

**Additional context**
Should be implemented as overlay (like it is in toast-notification)

**Comment by jeripeierSBB** [comment]
@Frenggi Should we deprecate the full screen loading indicator? From UX perspective, we don't consider a fullscreen loading indicator a good option. What is your opinion?

**Comment by mcilurzo** [comment]
I have the same opinion like @Frenggi. The User should always have a way to cancel a loading state (or an other action). If the loading process gets stuck, there is no way to call an other action.

**Comment by jeripeierSBB** [comment]
With #1116 we have deprecated the loading indicator mode fullscreen and won't fix the fullscreen loading indicator.

**Comment by sandrooco** [comment]
@jeripeierSBB & @mcilurzo: The fullscreen loading mode still is part of the [specification](https://digital.sbb.ch/en/websites/components/loading_indicator), see rule number 3.
Why is the fullscreen mode deprecated? I'm aware of your UX concerns, still have a legitimate case for using fullscreen mode though.

**Comment by mcilurzo** [comment]
i have updated the documentation. thanks for the reminder.
can you explain your case in more detail? what do you offer the user as a fallback if the reload fails?

**Comment by sandrooco** [comment]
@mcilurzo We load a bunch of media that will cover most of the screen (animated media, similar to a video). We can't display  it before everything is loaded. Fetching everything takes around 1-3 seconds depending on network conditions and cache availability.
If anything fails, we remove the loader and route the user back to the previous page.
