### ISSUE TITLE
Bug: Chromium based browsers outlines content of tabs by clicking

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#610]
**Describe the bug**
In chromium based Browsers the contents of the tabs component are outlined 
when clicking anywhere inside the tabs component element. The behaviour occurs only in chromium based Browser (Chrome, Edge (Chromium), Vivaldi...). Does not occur in other Browsers (Firefox, IE). 

**To Reproduce**
1. Go with chrome to 'https://sbb-angular.app.sbb.ch/business/components/tabs'
2. Go to 'Examples'
3. Click on 'Content 1' element

**Expected behavior**
Elements inside the Tab component should not get outlined

**Screenshots**
![chromium_bug_tabs_component](https://user-images.githubusercontent.com/50302840/94286242-076b5880-ff55-11ea-80d2-46a7e0ff889b.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium based (Chrome, Edge (Chromium), Vivaldi etc.)

**Comment by daniel-sc** [comment]
This happens as well for buttons (public) in mode "frameless":
![image](https://user-images.githubusercontent.com/117919/94393873-4f100100-015c-11eb-94c1-30b06bdeea1e.png)

**Comment by kyubisation** [comment]
This is the standard focus highlighting for chromium based browsers.
We can provide our own focus highlighting, but we have to be extremely careful with that for accessibility.

**Comment by daniel-sc** [comment]
If I understood https://blog.chromium.org/2020/09/giving-users-and-developers-more.html correctly it should be possible to use `:focus-visible` to show this bold outline only if needed (for keybord tab focus, ..) - compare the second code-pen on that blog post.

**Comment by daniel-sc** [comment]
Hi @kyubisation 
could you give an estimate if/when this will be fixed? 
We have several user complaining about this - so if this is not fixed here, we'd need to develop our own workaround.

**Comment by kyubisation** [comment]
We have not anaylzed this yet, so currently I cannot give you an estimate. I have assigned this a medium priority, so we will have a look at this soon.

**Comment by kyubisation** [comment]
@jeripeierSBB is currently working on fixing the issue with tabs: #627
As for buttons and links; We do not yet have a plan on how to approach this. UX is currently working on defining states and we will proceed once they have finished that.

**Comment by kyubisation** [comment]
Closed via #627
