### ISSUE TITLE
Bug: active tabs show bottom border in IE 

### ISSUE THREAD

**Issue by zer0p1** [sbb-design-systems/sbb-angular#611]
**Describe the bug**
Bottom border of active tab in IE not transparanet. In other browser the bottom border of active tabs are transparent

**To Reproduce**
1. Go to 'https://sbb-angular.app.sbb.ch/business/components/tabs'
2. Go to 'examples'

**Expected behavior**
Like in other browsers, IE should not show border bottom for active tabs.

**Screenshots**
![active_tab_border_bottom_ie](https://user-images.githubusercontent.com/50302840/94288102-56b28880-ff57-11ea-9cb4-95fc008a6af4.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Internet Explorer
 - Version: 11

**Comment by kyubisation** [comment]
We investigated this and this would require a minor to major refactoring of the tabs styling. Since IE11 is on its way out, I'm not sure how much effort should be put into a styling issue.
How important is this to your project?

**Comment by zer0p1** [comment]
Thanks for your investigation. The issue is not really important to our project and since it's only a small optical thing exclusively in IE, I suggest we close the bug as the effort is greater than the benefit seems to be.

**Comment by kyubisation** [comment]
Ok, thanks for the feedback. I will close this issue for now. Feel free to reopen, if your situation changes.
