### ISSUE TITLE
Bug: overflow on expansion panel breaks sticky elements

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#620]
**Describe the bug**
We have a sticky element inside an expansion-panel that we need to position 'sticky'. This fails as the expansion panel is (falsly!) detected as nearest scrolling ancestor, because it has `overflow: hidden`.

An analogous problem was already fixed for the process flow: #399

**Expected behavior**
The sticky element should be sticky based on the actual scrolling ancestor.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome 86
 - Version SACL 10.3.0

**Comment by kyubisation** [comment]
We analyzed this; We require the overflow: hidden due to the animation and cannot remove it.
Could you provide a reproduction? Maybe we can help in another way.

**Comment by zer0p1** [comment]
I created a reproduction: https://stackblitz.com/edit/angular-sbb-vhbzqa 
If you change the versions of angular-core and angular-public it works, and the yellow element behaves sticky. Thus, the a minor Version update of SACL broke the sticky i guess.
