### ISSUE TITLE
Bug: Tabs component lazy rendering creates new components for each input change

### ISSUE THREAD

**Issue by marcodev01** [sbb-design-systems/sbb-angular#638]
**Describe the bug**
The Tabs component creates a new component tree for each change of inputs of the tabs root component when lazy rendering is applied under unknown circumstances. This leads to many bugs that are difficult to find. Our components heavily rely on lifecycle hooks (e.g. [**first change**](https://angular.io/api/core/SimpleChange)). If a input change in a Tabs root component occurs, **first change** for exmple is true again since the component tree is created completly new.

I tried to reproduce the behaviour in an simple example in [stackblitz](https://stackblitz.com/edit/angular-sbb-kkezwu).
Unfortunately i was not able to reproduce the bug with a simple example. I assume the root cause is more complex, perhaps caused with complex project structures or libraries e.g. ngrx. In any case project intern we can reproduce the behaviour simply through enable lazy loading of tabs compoentent. Without lazy loading of abs component everything behaves as excpected.

**Expected behavior**
Lazy rendering of Tabs component should not create a new component tree for each input change. 
Alternatively the circumstance should be documented.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: all

**Additional context**
Note: We use **on push** change dectection.

**Comment by daniel-sc** [comment]
Hi,
actually this "bug" occurs when opening the currently acitve tab (redundantly) via `openTabByIndex`/`openFirstTab` - see this reproduction: https://stackblitz.com/edit/angular-sbb-yyrhyq?file=src%2Fapp%2Fapp.component.html

Of course the workaround is easy, but skipping the update within the component should be easy as well and would be my preferred solution :)

Best, Daniel
