### ISSUE TITLE
Feature request: Improved mobile view for usermenu

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#647]
The usermenu menu width in the mobile view should be as wide as the width of screen size (plus padding). Additional the animation should look like on www.sbb.ch

**Comment by sandrooco** [comment]
Is this issue already scheduled? We're having some issues with the usermenu on mobile - working around them with styling hacks isn't really sustainable though.

Primary issues:
- width (as described in original description)
- if positioned at the bottom of the screen, you're not able to see the usermenu's body when opening it (we wish a behavior similar to the language switch from https://sbb.ch)
- not being able to see display name on mobile

**Comment by jeripeierSBB** [comment]
as offline discussed with @sandrooco 

- issue with width should be addressed
- positioning at bottom of screen is currently not intended by design specs. Maybe opening above will be supported once sbb-usermenu ist implemented with future sbb-menu.
- Displaying user name on mobile can be done by css overrides

**Comment by jeripeierSBB** [comment]
@sandrooco Is there still something to be done with the usermenu of @sbb-esta/angular or can we close this issue?

**Comment by sandrooco** [comment]
Thanks for coming back to this issue!
We're currently cleaning up our migration to @sbb-esta/angular. I will try out the new usermenu as soon as possible and report back here, okay? Not sure if I can make it today - if not it will be next week.

**Comment by jeripeierSBB** [comment]
@sandrooco Thanks a lot :-)

**Comment by sandrooco** [comment]
So I tried it out today and it seems to cover all the asked items.
You can close the issue in my opinion.

**Comment by jeripeierSBB** [comment]
@sandrooco Thanks a lot for your tests. As suggested, we close this issue.
