### ISSUE TITLE
Feature request: Add a dollar icon

### ISSUE THREAD

**Issue by YanShopin** [sbb-design-systems/sbb-angular#689]
Could you please add the dollar icon to your collection
Like this https://github.com/primefaces/primeicons/blob/master/raw-svg/dollar.svg

Thank you,
Ian

**Comment by jeripeierSBB** [comment]
Hi @YanShopin
Thank you for your request. Icons are managed in the following repo: https://github.com/sbb-design-systems/icon-library
I already sent an email to the icon lib colleagues with a copy to you. So hopefully your request will be answered.

**Comment by luciegirardier** [comment]
Hi @YanShopin , Thank you for your request. We will add a dollar icon to the library in january. Best, Lucie

**Comment by luciegirardier** [comment]
Hi @YanShopin, FYI - two new icons are live for dollar in the library (coin-dollar, banknotes-dollar). Best, Lucie

**Comment by kyubisation** [comment]
We will provide a release of the library with this icon probably this week.

**Comment by jeripeierSBB** [comment]
Hi @YanShopin. With version 11.0.3 of sbb-angular library, the dollar icon is now available to you (https://angular.app.sbb.ch/core/icon-overview).
