### ISSUE TITLE
Feature request: Theming

### ISSUE THREAD

**Issue by timschoch** [sbb-design-systems/sbb-angular#70]
Theming the SACL (or our Applications in general) is currently cumbersome. There isn't a way to access the SCSS variables or change aspects of the design without knowing the internal structure of the components and css classes. To me, there are (atleast) three aspects to theming.

### 1. Switching between themes
For our cargo client portal we want to stick mostly to the default styling since it should be inline with the rest of the public SBB appearance. But for the data heavy stuff like tables we'll use the business styling. 

**Requirements (for us):**
- Choose a default theme for the whole application on a per component base
- Change the theme for a single component in a single view (can be done via an angular property or in SCSS)

### 2. Creating a Theme
This isn't a requriement for us, but I can see that in some circumstances it might be necessary or desirable to create an own theme. Eg. a Darkmode for Apps that are used in the driver's cabin.

### 3. Applying the theme to custom components
~~When building custom components there is curently no way to access the scss variables, functions and mixins. Thus we have to manually copy your variables to our own scss file, whichs is bad:~~ _(This is fixed in the current Version of SACL.)_

See [this comment](https://github.com/SchweizerischeBundesbahnen/sbb-angular/issues/70#issuecomment-508096981) for more information on using the SACL styles/themes for implementing custom components

### Food for thought
There are some conceptual questions that come to my mind:
- On one hand having multiple small files handling one aspect (colors, typo, grid, ...) would allow us to only include what we need. On the other hand this can lead to wrong import orders  resulting in unexpected behaviour. I've had this on a previous design system and it is very hard to debug and even harder to understand those dependencies.
- What level gets exposed? Only a hand full of basic variables or the full set?
- Do we use variables for theming and/or mixins for each components?
- Should we create local variables for each component or use the global ones? 
```scss
.sbb-button-hulk { color: $colorSuccess; }
// vs
$button-hulk-color: $colorSuccess;
.button { color: $button-hulk-color; }
```
The first option keeps the SCSS files neat and tidy, the later saves us from having to understand how the component is built. If we think of the (S)CSS as an API, the first one exposes the whole SCSS Code as an API while the second only exposes additional vars. Both options have pros and cons...

Here is an article by Hugo Giraudel outlining different approaches:
https://www.sitepoint.com/sass-theming-neverending-story/

**Comment by efux** [comment]
Concerning your third point: Why can't you import the styles.scss in your file and use the variables and mixins from there in your components?

```scss
@import "~node_modules/sbb-esta/angular-public/styles.scss";
```

Some of my thoughts concering the implementation of styling: #66 shows a way how the current styles could be overwridden. However the stylesheet gets verbose and both styles are sent to the client. The CSS selectors have to be very specific. This also makes changes to CSS classes and the HTML templates harder and errorprone.

The other approach would be like Angular Material to only include the paddings, borders, margins, etc. in the component's style and apply theme colors globally, which can be adapted with themes. However, this would require a major rewrite of the style sheets. I think long-term it would be beneficial.

**Comment by kyubisation** [comment]
@timschoch Thank you for the thourough feature request. 😃 
I'll try to categorize my thoughts:

### styles.scss
As @efux mentioned, we expose a styles.scss, which declares some global variables like colors and also includes mixins.
If there is something missing from this that you need, we can add it in a future release.

### Styling
I'm currently considering something similar to what @efux described for Angular Material.
This will require quite a bit of refactoring and will also have to be done really carefully, as to not introduce breaking changes too early. (Breaking changes may not be introduced before Angular 9).

However, it should generally be possible to use components from @sbb-esta/angular-public and @sbb-esta/angular-business at the same time and the styling depends on which variant was used.

### Theming rough plan
Currently the styling is done primarily through css classes. I would like to refactor this to use primarily lower level selectors (element, [attributes], ...) and assign css classes for color specific elements.

### Roadmap
My plan is to carry on with the refactoring mentioned before, as theming is currently really cumbersome, as it was not really considered during initial development.
This will however take quite some time and I cannot currently estimate, when an initial implementation will be done. I expect this will not be finished before (maybe even after) Angular 9 is released, which is expected in october.

**Comment by timschoch** [comment]
### styles.scss
On the first look the styles.scss in the current npm package covers everything we need. Was this added later on? I recall that it wasn't available in the early alpha or beta versions we started with and thus I had to copy all the variables over. Or I just overlooked it...
The current solution is what we where looking for and I'll create a task to refactor our scss. Thanks for pointing this out to me.

### Public Vars vs Public Component Structure
From an API standpoint it doesn't make a difference if you provide mixins, expose the css classes or use lower level selectors. The effect is that we (the consumers of the SACL) have to understand the HTML structure of the component in order to override it's appearance. Thus the whole rendering is a defacto public API and future changes to the DOM will be breaking changes. What this means for your ability to fundamentally evolve the library is obvious, especially once it gets widly adopted.

The only half-sane way (I can think of) to allow detailed control over a components visuals is to create detailed variables for each component. This exposes them to the public API and hides the actual implementation of the component.

To explain why this is even a real use case take the tooltip or popover for example: We want to increase the width to display our information in a readable way:
- Without vars we create our own more specific css class overwriting the default values.
- With mixins we will override the elements in the mixin.
- With variables we set the corresponding value.

The underlying question is _what does theming mean to you_?
It really depends on the level of freedom you want to give us to tweak the design system. Do you want to restrict the public API to a hand full of variables for colors and paddings? Or should we be able to customize the components in-detail? This is a strategic decission.

Now, to be really honest... either way you decide, we'll change the width of the Tooltip anyway ;) The difference is if you don't expose this option as a public API in one form or another we take the risk of breaking our UI with future SACL updates.

### Styling
One thing that it don't see @efux's approach cover nicely is creating custom components. Let's assume we build our own weekpicker (#26) and I want it to look exactly as the default datepicker. This is only possible if I get access to detailed component variables or if you provide mixins for each element of a component.

With your approach I can't think of another way other than to emulate your html structure and use the exact same CSS classes. If you update the SACL my component will break. Most likely without me knowing it because we won't do a full regression test of the whole UI each time we update the SACL.

### Roadmap
I'm happy to wait a bit as I prefer a solid implementation over a quick and dirty one. 👍

**Comment by kyubisation** [comment]
### styles.scss
We have added this a while ago and added information to Getting Started at the end. However it is not documented and currently has quite some duplication contained within. There is also the matter, that I would like to namespace the variables, functions and mixins (sbb...) but I didn't have the time to finish that for release 8.0.0 and now I have to wait for 9.0.0.

### Theming
My intention is essentially to provide a mixin to define custom colors. In the background this would target specific css classes in the components and override the default colors due to css specificity.

As for theming support; angular-public will have very little theming support, since the intention here was to have a unified presentation. I will not (and cannot) stop you from changing the styling anyway though. 😄 
angular-business might have more theming support, but at the current time it is not there yet.
In any case I will document breaking changes to the best of my knowledge.
I can also expose more of the component specific variables and mixins in a future release, however currently they also lack namespacing and I would like to fix that before releasing them.

Generally speaking at the current time I will be fairly restrictive with theming support, simply due to the fact that I lack the ressources to provide better support. 😞 
I will bring up this topic in the UX Design Systems coordination meeting next week.

**Comment by efux** [comment]
@kyubisation The exposal of component specific mixins (e.g. buttons) in a future release would be a great thing. This would help in extending components, which are visually similar to existing ones.

**Comment by kyubisation** [comment]
@efux I'll see what I can do.

As a workaround on how to currently style components:
You can add an id to html or body (e.g. sbb-style) and use that in css rules. This way the rule has a higher specificity and is applied.

```html
<body id="sbb-style">
```

```css
#sbb-style .sbb-button {
  background-color: blue;
}
```

**Comment by timschoch** [comment]
Sorry, for going silent for a week.
I haven't had the time to test out the new styles.scss file, but will give it a shot and will report back, if it doesn't work.

After remembering our talk from some time ago I understand and support the reasoning behind not allowing much customisation or theming. Having a Mixin (or even exposing the variables) to set some basic values seems fine to me. 

Maybe I should change the title to something along the line of "expose styling for custom components"?
Personally I prefer having access to the (read only) variables over the mixin approach @efux is promoting here. It does work fine for slight alternatives of existing components, but is limited when building complex custom components.

Regarding the namespacing of the vars, do you already have a concept in place and it's just a matter of getting things done?

**Comment by kyubisation** [comment]
@timschoch No worry. At least from my side, there is no time constraint for this. 😃 

From what I understand from the two of you, is that exposing more of the sass part might be an easy first step.
In regards to the namespacing; It is primarily just getting things done. The concept is basically naming everything consistently and with the sbb prefix.

**Comment by timschoch** [comment]
> From what I understand from the two of you, is that exposing more of the sass part might be an easy first step.
Yes, that would be helpful on a per-component level.

**Comment by jeripeierSBB** [comment]
Partially possible now with css properties and standard / lean design variants.
