### ISSUE TITLE
Feature request: altText attribute for sbb-icon

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/sbb-angular#701]
**Is your feature request related to a problem? Please describe.**
In case the client looses the internet connection, we'd like to show a Ghettobox. At this point it's obviously impossible to load the "close icon".

**Describe the solution you'd like**
For that case it would be nice to be able to provide a short text similar to the `img` tags' `alt` attribute.

**Describe alternatives you've considered**
I thought about providing a custom [ErrorHandler](https://angular.io/api/core/ErrorHandler) - this doesn't really make sense though because it would pollute the project immensely (especially if there are multiple cases).

**Additional context**
Screenshot of the Ghettobox without close icon because it couldn't be loaded.
<img width="894" alt="Screenshot 2021-01-19 at 15 12 44" src="https://user-images.githubusercontent.com/25688064/105045971-cac5ee80-5a68-11eb-9e9f-0988fb88499a.png">

**Comment by kyubisation** [comment]
You can preload icons by injecting `SbbIconRegistry` in your root component and calling `getNamedSvgIcon('cross-small', 'kom')`. The icon registry stores once loaded icons in memory.

e.g. (untested)
```ts
constructor(registry: SbbIconRegistry) {
  forkJoin([
    registry.getNamedSvgIcon('cross-small', 'kom'),
    registry.getNamedSvgIcon('arrow-long-right-small', 'kom'),
    registry.getNamedSvgIcon('info', 'fpl'),
  ]).subscribe();
}
```

**Comment by sandrooco** [comment]
@kyubisation Nice, that works! Thanks a lot.
