### ISSUE TITLE
Missing null/undefined-check in breadcrumb component

### ISSUE THREAD

**Issue by sdbuehlmann** [sbb-design-systems/sbb-angular#705]
When the breadcrumbs are defined dynamically (in a for loop), the Breadcrumb-Component throws an error.

I was doing the following:
```
<sbb-breadcrumbs>
  <sbb-breadcrumb>
    <a routerLink="/" routerLinkActive="sbb-selected">
      <sbb-icon-house></sbb-icon-house>
    </a>
  </sbb-breadcrumb>
  <sbb-breadcrumb *ngFor="let level of levels">
    <a [routerLink]="level.route" routerLinkActive="sbb-selected">{{level.name}}</a>
  </sbb-breadcrumb>
</sbb-breadcrumbs>`
```

This throwed an exception:
ERROR TypeError: Cannot read property 'first' of undefined
    at SbbBreadcrumb.get isFirst [as isFirst] (breadcrumb.component.ts:74)
    at SbbBreadcrumb_Template (breadcrumb.component.ts:58)
    at executeTemplate (core.js:9323)
    at refreshView (core.js:9192)
    at refreshComponent (core.js:10358)
    at refreshChildComponents (core.js:8989)
    at refreshView (core.js:9242)
    at refreshEmbeddedViews (core.js:10312)
    at refreshView (core.js:9216)
    at refreshComponent (core.js:10358)

On the following line should probable be a null/undefined-check for `this._parent.levels`:
https://github.com/sbb-design-systems/sbb-angular/blob/92c3c547dd4c30d9366e45d464c11da26720a320/src/angular-public/breadcrumb/breadcrumb/breadcrumb.component.ts#L74

**Comment by sdbuehlmann** [comment]
We have found a little workaround: We provide `levels` in a Promise and use `async` pipeline in `ngFor`:
```
levels: BreadcrumbLevel[]  = [
    new BreadcrumbLevel("Dashboard", "/dashboard"),
    new BreadcrumbLevel("Meine Projekte", "/dashboard/my-projects"),
  ];
  levelsPromise: Promise<BreadcrumbLevel[]> = Promise.resolve(this.levels);
```

```
<sbb-breadcrumbs>
  <sbb-breadcrumb>
    <a routerLink="/" routerLinkActive="sbb-selected">
      <sbb-icon-house></sbb-icon-house>
    </a>
  </sbb-breadcrumb>

  <sbb-breadcrumb *ngFor="let level of levelsPromise | async">
    <a [routerLink]="level.route" routerLinkActive="sbb-selected">{{level.name}}</a>
  </sbb-breadcrumb>
</sbb-breadcrumbs>
```

With this hack, the described exception is not thrown and the breadcrumbs are rendered as expected.

**Comment by kyubisation** [comment]
We will have a look at this as soon as we can.
We would also appreciate a PR.

**Comment by jeripeierSBB** [comment]
@sdbuehlmann We found the problem and implemented a fix. Please note, that you use a deprecated version of angular icons. See [https://angular.app.sbb.ch/icons/introduction/getting-started](https://angular.app.sbb.ch/icons/introduction/getting-started) for how to migrate.
