### ISSUE TITLE
Bug: sbb-header missing left padding

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#707]
sbb-header title should have an offset of 54px from the left screen border (see https://digital.sbb.ch/de/webapps/modules/header).

OK
![image](https://user-images.githubusercontent.com/78031737/105859703-20604500-5fed-11eb-93ce-afe61c4c2e39.png)

NOK
![image](https://user-images.githubusercontent.com/78031737/105859713-23f3cc00-5fed-11eb-85ce-cf6f4a618e25.png)

origin issue: #704

**Comment by teosbb** [comment]
https://github.com/sbb-design-systems/sbb-angular/issues/724
