### ISSUE TITLE
Bug: The options list within an sbb-select component is not scrolled down to the previously selected option

### ISSUE THREAD

**Issue by vitalyperev** [sbb-design-systems/sbb-angular#723]
**Describe the bug**
The behavior of the `sbb-select` component has been changed in the new version (11.2.0). When opening a long options list, it is not scrolled down to the selected item anymore (which is important for our use case). 

**To Reproduce**
1. Go to https://angular-umr8r6.stackblitz.io/
2. Click on the select element.
3. Notice that the options list is not scrolled down to the selected element (50).

**Expected behavior**
The previously selected option should appear when clicking on the select element, as it was in version 10.3.2.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4324.150

**Comment by jeripeierSBB** [comment]
Hi @vitalyperev Thanks for your bug report. Coincidentally, we just discovered the bug today and I'm working on fixing it. With the next release it should work again.
