### ISSUE TITLE
Bug: Header has no padding when navigation icon is missing

### ISSUE THREAD

**Issue by teosbb** [sbb-design-systems/sbb-angular#724]
**Describe the bug**
Header has no padding when navigation icon is missing.

![image](https://user-images.githubusercontent.com/61213516/108230417-0e337b80-7141-11eb-87d4-3d3e2604dcc7.png)

When the screen is smaller:

![image](https://user-images.githubusercontent.com/61213516/108230455-1b506a80-7141-11eb-81ed-94eb53703e8b.png)

**To Reproduce**
1. Add a header
2. make the window smaller (width) so that the sidemenu appears.

**Expected behavior**
The Title should stay where it is with a padding left of 54px

**How to fix**

in file:
https://github.com/sbb-design-systems/sbb-angular/blob/2b2f3ddbd16668eaa04f90b5ebbf501161547653/src/angular-business/header/header/header.component.scss

**line: 69**

replace 
display: none 

with:  visibility: hidden;

.sbb-header-open-menu:not(.sbb-header-app-chooser-available) {
  @include mq($from: desktop) {
    **visibility: hidden;**
  }
}

visibility hidden should maintain the icons width and make a desired padding
after the fix:
![image](https://user-images.githubusercontent.com/61213516/108231227-d5e06d00-7141-11eb-9b04-46d27c561b1c.png)

**Comment by kyubisation** [comment]
Closed via #732
