### ISSUE TITLE
Bug: notification: icon should not be centralized

### ISSUE THREAD

**Issue by GreenRover** [sbb-design-systems/sbb-angular#725]
**See this screenshot**
![image](https://user-images.githubusercontent.com/512850/108322622-f94cfb80-71c5-11eb-8818-c654f126e227.png)

**Expected is**
https://sbb.sharepoint.com/sites/tms/uebergreifend/Forms/AllItems.aspx?csf=1&web=1&e=V9HGlN&cid=d1791bd6%2Dbe09%2D4765%2D9845%2D8b502e44e194&FolderCTID=0x012000738E4BC220E3A84FBF4EF95D32150685&id=%2Fsites%2Ftms%2Fuebergreifend%2F700%20TMS%2F50%5FUser%5FExperience%2F15%5FProjekte%20ohne%20Filer%2FSelfServicePortal%2FSelf%5FService%5FPortal%2FBrokers%2FBrokers%5Ftable%5Fempty%2Epng&parent=%2Fsites%2Ftms%2Fuebergreifend%2F700%20TMS%2F50%5FUser%5FExperience%2F15%5FProjekte%20ohne%20Filer%2FSelfServicePortal%2FSelf%5FService%5FPortal%2FBrokers

That the "info" icon is in the top left corner.

**Comment by jeripeierSBB** [comment]
checked with @Frenggi : icon should be on top as @GreenRover suggested
