### ISSUE TITLE
Bug: SBB-Header mit SBB Table Sticky zusammen

### ISSUE THREAD

**Issue by teosbb** [sbb-design-systems/sbb-angular#742]
**Describe the bug**
Wenn Mann ein Position: sticky auf das table theader th setzt und mann gleichzeitig ein sbb-header aktiviert hat funktioniert es nicht

Grund dafür ist wie es aussieht dass wenn es irgendein element gibt mit:
    position: fixed;
    top: 0;

auf der seite funktioniert position: sticky nicht mehr

**To Reproduce**
1. Add header component
2. Add Table component
3. define: table thead th { position: sticky; top: 0; }

**Expected behavior**
Sticky table header should work

**Additional context**

In my sample the table is "fixed" on the screen and not scrollable with the scroll of the window.

I can image that there are cases when the header and the sticky table header will scroll together overlaping each other but it's also confusing that sticky does not work if the header is fixed.

Maybe the header should not be position: fixed but the developer should choose how to position it.

problem is it's a breaking change.

In My specific case changing the position: fixed to position: absolute will solve the problem.
Maybe this could be configured.

Proposal:
- Add to documentation:
header property:
[stickyTableHead]="true" > warning in docs that position fixed should be disabled in the header component in order to work 
[fixedHeader]="false" new peoperty to disable the header fixed top: 0

**Comment by jeripeierSBB** [comment]
@teosbb is looking for a reproduction

**Comment by teosbb** [comment]
@jeripeierSBB maybe the top:0 has caused the problems. I will get access to the app in the following few days
