### ISSUE TITLE
Bug: sbbInput disables placeholder

### ISSUE THREAD

**Issue by ClaudioZesiger** [sbb-design-systems/sbb-angular#748]
**Describe the bug**
When using sbbInput on an input field, the placeholder will not be visible.

**To Reproduce**
1. Create a simple HTML input field with a placeholder and sbbInput
2. Open the frontend
3. The placeholder text will not be shown

**Screenshots**
With sbbInput
![image](https://user-images.githubusercontent.com/37439828/110074458-86c14b80-7d81-11eb-898e-2029f4d64466.png)

    <div id="jobSearchRow" class="row">
        <input type="text" sbbInput class="align-right" placeholder="{{ 'JOB_OVERVIEW.SEARCH' | translate }}" (keyup)="filterData($event)" />
    </div>

Without sbbInput
![image](https://user-images.githubusercontent.com/37439828/110074501-9a6cb200-7d81-11eb-8e3d-e571c2c55f52.png)

    <div id="jobSearchRow" class="row">
        <input type="text" class="align-right" placeholder="{{ 'JOB_OVERVIEW.SEARCH' | translate }}" (keyup)="filterData($event)" />
    </div>

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [88.0.4324.190]

**Comment by jeripeierSBB** [comment]
Hi @ClaudioZesiger 
The sbbInput directive should always be used with a sbb-form-field wrapper. Starting with version 11 you should see an exception in your console. Can you check that? If not, which version do you use? Does the bug still exist, if you use sbb-form-field?

**Comment by jeripeierSBB** [comment]
@ClaudioZesiger My statement was not correct: it is the opposite way: a sbb-form-field requires a sbbInput, but an sbbInput can be used standalone. We could reproduce your bug and we will provide a solution soon. Thanks for creating this issue!

**Comment by ClaudioZesiger** [comment]
Many thx for fixing this to jeripeier. :-)
