### ISSUE TITLE
feat(public): footer

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-angular#75]
Design Spec: https://digital.sbb.ch/en/websites/modules/footer
Also see sbb.ch for reference implementation

API Spec:

- Selector: sbb-footer
- Support up to four sections
  - Selector: sbb-footer-section
- Support language links with a component that supports a RouterLink (See GhettoboxComponent for reference) or a href Input
  - Selector: sbb-footer-language-link
  - This should internally render an a tag
- Support other links with a component that supports a RouterLink (See GhettoboxComponent for reference) or a href Input
  - Selector: sbb-footer-link
  - This should internally render an a tag
- Support custom logo
  - Selector: sbb-footer-logo

```html
<sbb-footer>
  <sbb-footer-section label="Kontakt>
    ...
  </sbb-footer-section>
  ...
  <sbb-footer-language-link [href]="deLink">de</sbb-footer-language-link>
  <sbb-footer-language-link [href]="enLink">en</sbb-footer-language-link>
  ...
  <sbb-footer-link routerLink="/impressum">Impressum</sbb-footer-link>
  <sbb-footer-link routerLink="/about">About</sbb-footer-link>
  <sbb-footer-logo>
    <img src="assets/logo.png">
  </sbb-footer-logo>
</sbb-footer>
```

**Comment by jeripeierSBB** [comment]
Won't do without specific demand.
