### ISSUE TITLE
Bug:  FormField placeholder attribut binding doesn't work

### ISSUE THREAD

**Issue by marcodev01** [sbb-design-systems/sbb-angular#756]
**Describe the bug**
Since v11 placeholder attribut binding doesn't work anymore. however native placeholder are working as expected.

**To Reproduce**
see reproduction: https://stackblitz.com/edit/angular-e6hahm

**Expected behavior**
Should work with attribut binding as well

**Comment by kyubisation** [comment]
See #748
Should be fixed with #749, which we will release next week.

**Comment by marcodev01** [comment]
Awesome, thanks for the quick response :)
