### ISSUE TITLE
Bug: Icon in autocomplete option not correctly aligned

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#780]
**Describe the bug**
When using an icon alongside text in an autocomplete option, the icon is not aligned correctly.

Code:
```
      <sbb-option i18n="@@LOADING_UNIT_CREATE_NEW" [value]="CREATE_NEW_LOADING_UNIT">
        <sbb-icon svgIcon="kom:plus-small"></sbb-icon>
        <span>Neue Ladeeinheit erfassen</span>
      </sbb-option>
```
Result:
![image](https://user-images.githubusercontent.com/117919/113822288-8a2f6480-977d-11eb-9325-74457421e5e4.png)

This is probably due to multiple/inconsistent margins/translations:
![image](https://user-images.githubusercontent.com/117919/113822521-d084c380-977d-11eb-97ff-40ca45666cd2.png)

**To Reproduce**
See example above

Provide a reproduction with StackBlitz (e.g. use the StackBlitz buttons on the examples).

**Expected behavior**
Icon an text should be aligned correctly (vertical center)

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome 89
 - Version SACL 11.1.3

**Smartphone (please complete the following information):**

**Comment by daniel-sc** [comment]
Nur bei "Deskop" Auflösung - bei 5k ist alles korrekt

**Comment by jeripeierSBB** [comment]
We postpone this issue and will investigate further on not centered icons

**Comment by jeripeierSBB** [comment]
Should be resolved: <img width="320" alt="Bildschirmfoto 2022-01-27 um 10 53 56" src="https://user-images.githubusercontent.com/29278232/151335338-29c21c43-a5e0-4c0b-8d51-df311f918323.png">

But: Icons have still to be in a 24px grid, so e.g. the plus icon is not exactly centered, but shifted by 0.5px. But as my screenshot shows, the alignment is much better than in your screenshot.

Please reopen if I am wrong.
