### ISSUE TITLE
Feature request: css class to apply spacing of a not existing label

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/sbb-angular#783]
**Is your feature request related to a problem? Please describe.**
If you have for example the following group of form fields, you have to place the button yourself, that it is aligned with the input fields.
![image_2021-04-07_17-23-12](https://user-images.githubusercontent.com/29278232/113892099-fb930580-97c5-11eb-8c56-13a378494e70.png)

**Describe the solution you'd like**
A css class to apply to the button (or other element) would ensure the correct top margin (height of label).

**Comment by kyubisation** [comment]
Implemented by #1075
