### ISSUE TITLE
Bug: Tooltip delay don't work if injected by SBB_TOOLTIP_DEFAULT_OPTIONS

### ISSUE THREAD

**Issue by marcodev01** [sbb-design-systems/sbb-angular#790]
**Describe the bug**
The tooltip delays don't work as specified if injected by SBB_TOOLTIP_DEFAULT_OPTIONS.
On the other hand if the delays are set by attribute it works as expected.

**To Reproduce**
See Reproduction: https://stackblitz.com/edit/angular-uzgvep-1bdl3o

**Comment by jeripeierSBB** [comment]
Hi @marcodev01 Thanks for your bug report. At the moment, only the directive variant of the tooltip does support provided default options. With the ongoing merge of public and business (#684), we will address this issue.
