### ISSUE TITLE
Bug: business stackblitz examples throw error

### ISSUE THREAD

**Issue by trimm-b** [sbb-design-systems/sbb-angular#798]
https://stackblitz.com/angular/nndgexjynej?file=src%2Fapp%2Fforms-chip-input-example.ts

throws Error

Error in /turbo_modules/@sbb-esta/angular-business@11.1.3/bundles/angular-business-header.umd.js (1018:17)
SbbHeader is not defined

**Comment by jeripeierSBB** [comment]
First finding: All business examples do not work in stackblitz anymore.

@trimm-b As a little workaround you can remove "SbbHeaderModule" in "modules" array in the sbb-business.module.ts file, as long as you don't like to use a sbb-header in your stackblitz example.
