### ISSUE TITLE
Bug: Autocomplete should disable Chrome autofill

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#824]
**Describe the bug**
For certain label/names Chrome displays an autofill (see screenshot) - this is annoying for the user, as it covers the actual options:
![image](https://user-images.githubusercontent.com/117919/120773225-6db36c80-c521-11eb-957f-dfb0664767ba.png)

**To Reproduce**
Ask me - I'll show you :)
(Apparently this is not easy to reproduce, as the browser only does this after many similar inputs to the same field?!?)

**Expected behavior**
The Chrome autofill should be prevented by default. 
Optionally the autofill could be enabled via an attribute.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 91

**Comment by kyubisation** [comment]
Looking at https://adamsilver.io/blog/stopping-chrome-from-ignoring-autocomplete-off/ and https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion I'm not quite sure how to deal with this.

We assign `autocomplete="off"` and an incrementing id (e.g. `id="sbb-native-input-0"`). We could potentially also set the name attribute to a random value (if not previously set).

@daniel-sc Could you check if assigning a random name attribute solves this problem?

**Comment by daniel-sc** [comment]
Hi @kyubisation 
thanks for looking into this! It seems random names do not help:

![image](https://user-images.githubusercontent.com/117919/120783998-e9b2b200-c52b-11eb-9160-2ba599015572.png)

Any other ideas?

**Comment by kyubisation** [comment]
Reading through https://bugs.chromium.org/p/chromium/issues/detail?id=914451is extremely frustrating. The stance by the Chromium team seems to be "We know better".
There are two suggested workarounds (from other developers):
- Add a `<input class="hidden" tabindex="-1" aria-hidden="true">` before the input and hide it (Gmail seems to use this)
- Add a focus handler which sets the autocomplete attribute to `no`: `<input #a1 (focus)="a1.setAttribute('autocomplete', 'no')" [sbbAutocomplete]="autocomplete">`

I'm not sure whether there is something we can do in this situation.

**Comment by daniel-sc** [comment]
It seems that using a complete random `name` attribute solves this in our case, whereas just postfixing a fixed name with a random string does not. Wondering how long/short the prefix needs to be for activating chrome autocomplete... 

Anyhow - I see this is a bigger mess - I agree that there is not much else to do from your side. Maybe add some documentation to the SBB Autocomplete to help others with that?
