### ISSUE TITLE
Bug: Expansion Panel Header configurable tabindex

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#838]
**Describe the bug**
When the expansion panel header is not disabled, it has always `tabindex=0`. This hinders a natural tabindex flow for long forms that are structured using accordions - e.g.:
![image](https://user-images.githubusercontent.com/117919/124729848-15e99600-df11-11eb-87b8-5a62dda7af90.png)

It should be possible to set `<sbb-expansion-panel-header tabindex="-1">` (or similar) to exclude the expansion panel header from the tab index flow.

**Comment by kyubisation** [comment]
I'm not quite sure I understand this correctly?
As far as I understand your request, this would break accessibility, which I'm hesitant to support.

**Comment by kyubisation** [comment]
Directly discussed with @daniel-sc.
We will add an @Attribute decorator, which will allow the tabindex to be set on `<sbb-expansion-panel-header>`.
