### ISSUE TITLE
feat(business): status

### ISSUE THREAD

**Issue by kyubisation** [sbb-design-systems/sbb-angular#86]
Design Spec: https://digital.sbb.ch/en/webapps/components/status

API Spec:
- Selector: `sbb-status`
- Input() type: 'valid' | 'warning' | 'invalid' | string
- Input() message?: string // The optional message

DoD:
- Component implemented
- Documentation provided

**Comment by timschoch** [comment]
Wir haben Datenintensive Ansichten bei denen wir einen Status darstellen müssen und wo wir uns eine reduziertere Darstellung wünschen.

Aktuell nutzen wir einen 8px Kreis:
![grafik](https://user-images.githubusercontent.com/10527318/62218298-73334f00-b3ac-11e9-9282-dce3cbda37bf.png)

Damit der Status für alle verständlich ist, wäre ein optionales Tooltip (mit opt. Delay) hilfreich, in dem der Status erklärt werden kann.
