### ISSUE TITLE
Bug: Textarea jumps/leads to scrolling on input

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#862]
**Describe the bug**
when having longer input (many lines) in the textarea it sometimes leads to unintended scrolling.

**To Reproduce**
1. Go to https://angular.app.sbb.ch/public/components/textarea
2. Click on "Showcase"
3. Enter multiple lines
4. Scroll so that only last few lines are visible
5. Enter empty lines and text
6. See that sometimes the scrollbar jumps (not easy to reproduce)

**Expected behavior**
Scrolling should be consistent and not jumping up and down

**Screenshots**
![jumping-textarea](https://user-images.githubusercontent.com/117919/129368079-3666efec-303f-4c9f-9cf1-55296fa8a01e.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome  92.0.4515.131 (Offizieller Build) (64-Bit)
 - Version SACL 12.3

**Additional context**
In our project (with perfect-scrollbar) this can always/easily be reproduced!
Maybe related: https://stackoverflow.com/questions/56329625/preventing-textarea-scroll-behaviour-in-chrome-after-newline-added

**Comment by jeripeierSBB** [comment]
Hi @daniel-sc . Thanks for the issue. I could reproduce it. It needs a lot of content then it seems to always happen. We need some time until we can have a deeper look.

**Comment by daniel-sc** [comment]
Hi @jeripeierSBB 
Thanks for looking into it! As this happens regularly in our app (maybe because of smaller width?), we'd appreciate if you could give a more concrete timeline, to decide if we need to investigate further on our own 🧐

**Comment by kyubisation** [comment]
So, we investigated this a bit more in depth. We were able to solve part of the problem. 
However, when only the bottom part of the textarea is visible it might still scroll to the cursor position. This behaviour is internal to the CDK Autosize directive and cannot be easily changed. If this is a problem, I have added an input `autosizeDisabled` to completely disable the autosize.

**Comment by daniel-sc** [comment]
Sounds sensible. If you cut a (pre-)release I'll try it out!
