### ISSUE TITLE
Bug: business checkbox label not correctly aligned

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#878]
**Describe the bug**
Sometimes(?) the label of the checkbox in the business variant is not correctly center/baseline aligened, but is a shifted a little to the top - see screenshot:
![image](https://user-images.githubusercontent.com/117919/132495216-fe11672e-5989-4c51-a745-0d3d86066244.png)

**To Reproduce**
1. Go to https://angular.app.sbb.ch/business/components/checkbox
2. Click on Examples
3. Check position of label "Disable All"

**Expected behavior**
Label should be vertically centered with checkbox

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: win10
 - Browser Chrome 93.0
 - Version: SACL 12.3.0

**Comment by jeripeierSBB** [comment]
Hi @daniel-sc 
At the moment we were unable to reproduce this issue. Can you maybe provide a reproduction with stackblitz?

**Comment by daniel-sc** [comment]
@jeripeierSBB Can't you reproduce the screenshot above from the showcase? At least on my phone it still looks the same.

**Comment by jeripeierSBB** [comment]
@daniel-sc thanks for the hint, on my phone it looks wrong too. On desktop computers we were not able to have the situation like on the screenshot.

**Comment by jeripeierSBB** [comment]
@daniel-sc On windows with Chrome we still can't reproduce the issue. On Safari on iOS we can reproduce the issue and it seems to be a problem with safari mobile. Did you really encounter the problem on Windows Chrome? If you like you can contact us on Teams to show us the problem.

**Comment by daniel-sc** [comment]
Screen: Windows-Zoom: 125%, Resolution: 1920x1080
