### ISSUE TITLE
Feature request: New input for SbbChipModule 

### ISSUE THREAD

**Issue by Marco-Ishiguro** [sbb-design-systems/sbb-angular#881]
Dear team,

**Problem**
Chip module don't check if the text typed exist in the option.

**How to reproduce :** 
1. Go to https://angular.app.sbb.ch/business/components/chip
2. In the last example Autocomplete Chip Input Example type "12345" 
3. Press enter
4. A chip is created even if it wasn't in the option list

**Problem**
Based on our understanding and experience from the lib, there is currently no option to avoid that behavior

https://github.com/sbb-design-systems/sbb-angular/blob/master/src/angular-business/chip/chip-input/chip-input.component.ts

```
 /** Handle the keydown event. */
  _handleKeydown(event: KeyboardEvent) {
    const keyCode = event.keyCode;
    const currentValue = this._inputElement.nativeElement.value;
    if (keyCode !== ENTER || !currentValue) {
      return;
    }

    event.preventDefault();
    if (this.autocomplete) {
      if (!this.autocomplete.options.some((opt) => opt.active)) {
        this._onSelect(currentValue);
      }
    } else {
      this._onSelect(currentValue);
    }
  }
```

The problem being that` if (!this.autocomplete.options.some((opt) => opt.active)) this._onSelect(currentValue); ` will create a chip even if not in the options

**Potential solution**
A solution would be a documented **@input** to on/off this behavior (Any default value is ok for us).

**Our temporary hack to work around it**
We was able to work around the problem with a temporary hack (has you can see it's not the kind of code we should let in our application) (We have another event handler that do the selection logic for us) : 

```
  sbbChipInput: SbbChipInput;
  @ViewChild('chipInput') set sbbChipInputEvent(sbbChipInput: SbbChipInput) {
    if (sbbChipInput) {
      this.sbbChipInput = sbbChipInput;
      // Since SBBChips do not allow blocking entries not present in options, we built a temporary hack
      // https://github.com/sbb-design-systems/sbb-angular/blob/master/src/angular-business/chip/chip-input/chip-input.component.html
      // https://github.com/sbb-design-systems/sbb-angular/blob/master/src/angular-business/chip/chip-input/chip-input.component.ts
      // if (!this.autocomplete.options.some((opt) => opt.active)) { this._onSelect(currentValue); }
      // To avoid that we disable the ESTA handler and build ours on top
      setTimeout(() => {
        // This is very hacky, TODO remove when feature treated
        const inputChipTextBox = [...this.sbbChipInput._elementRef.nativeElement.childNodes].find(element => element.tagName === 'INPUT');
        inputChipTextBox.eventListeners().forEach(listener => {
          inputChipTextBox.removeEventListener('keydown', listener);
          inputChipTextBox.addEventListener('keydown', (event: KeyboardEvent) => {
            if (event.code === 'Tab') {
              this.sbbChipsAutocomplete.keyManager.tabOut.next();
              return;
            }
            if (event.code === 'Enter') {
              return;
            }
            listener(event);
          });
        });
      });
    }
  }
```

The implementation of the feature would really help us. 

Let us know if we can do anything or provide more details.

Thank you for everything

Best regards

Marc (ZIS team)

**Comment by jeripeierSBB** [comment]
Hi @Marco-Ishiguro 
I think with our "merged" library (not released yet, probably with Angular 13) there is a much easier option by binding an event handler to "chipInputTokenEnd" output where you manually can control what happens with your entered tokens. So a filter to your available options would be possible there. Is this new implementation sufficient for you? You can preview the documentation here: https://staging-sbb-angular.app.sbb.ch/882-merge/angular/components/chips/api (stackblitz examples won't work)

**Comment by Marco-Ishiguro** [comment]
Hi @jeripeierSBB ,

Thank you for the fast response,. 

Sound good to me, we have a work around until there.
(If I get it right would be around November or December -> Angular 13 release ?)

Small side question, will the new merged lib comes with a lot of breaking change in the components API ? (In order for us to plan the right amount of time for the migration).

Thank you for everything

Best regards

Marc

**Comment by kyubisation** [comment]
Hello @Marco-Ishiguro 
That timeline seems about right.
In regards to breaking changes; Yes, there will be quite a few breaking changes in order to increase the flexibility and consistency of the library. However, the automatic migrations should take care of most cases.

**Comment by Marco-Ishiguro** [comment]
Thank you for the fast answer, I'm looking forward to use this new version.
