### ISSUE TITLE
Feature request: Tooltip preferred position

### ISSUE THREAD

**Issue by daniel-sc** [sbb-design-systems/sbb-angular#889]
**Is your feature request related to a problem? Please describe.**
We use the tooltip in the icon bar - there we'd prefer it to appear on the right, so it does not overlap the next icon:

![image](https://user-images.githubusercontent.com/117919/137101796-b3d99afa-c54c-43f4-aa19-eb552ab27e74.png)

**Describe the solution you'd like**
A new input to the tooltip - e.g. `preferredPosition: 'top' | 'bottom' | 'left' | 'right'` that is honored if there is enough space available. Otherwise it should fall back to the original/current postitioning.

**Comment by Frenggi** [comment]
I agree, until now we havn't thought about this. But from the UX perspective, this request is totally understandable. Therefore I would propose to support this new property.
@kyubisation: I try to add this to the UX specification this afternoon.

**Comment by AndreKoepke** [comment]
It seems to me, that this is the right ticket. If is not the case, then I will open a new ticket.

I want to set a position to a tooltip and I'm unsure how to do it. There is a exported type about the position, but it seems, that it is not be used for the API. 
https://github.com/sbb-design-systems/sbb-angular/blob/2069df63851628b38e44a103957e42b5c155ccfc/src/angular/tooltip/tooltip.ts#L53. 
Am I wrong?

**Comment by mhaertwig** [comment]
@AndreKoepke, you're right that there is currently no way to change the position of the tooltip in SBB Angular. I am increasing the priority of the issue and see what we can do.
