### ISSUE TITLE
Bug: Date widget - wrong behaviour in read-only state

### ISSUE THREAD

**Issue by FlorianGebhardSBB** [sbb-design-systems/sbb-angular#916]
**Describe the bug**
Date widget behaves wrongly when in read-only state. 
Compare specification with screenshot below.
Spec = https://digital.sbb.ch/en/webapps/components/datepicker 

**Expected behavior**
![image](https://user-images.githubusercontent.com/94061189/141133023-d0c9bd9c-9cf5-4201-a158-711e6cf919f6.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/94061189/141132890-8aa5cfd6-2c21-45ec-b122-c1a3081703ba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Date Widget:
•	Lässt sich trotz «read-only» Status öffnen und ein anderes Datum auswählen.
•	Das neue Datum (z.B. 6. Nov. 2021) wird ins Feld übernommen.
•	(kann aber natürlich nicht gespeichert werden, da unsere Applikation im Read-only-Mode keinen Speichern-Button anbietet)

Antwort von Franco Ehrat:
•	Date Widget: absolut einverstanden. Das Verhalten stimmt da noch nicht mit der UX Spezifikation überein. --> Bug

**Comment by jeripeierSBB** [comment]
@FlorianGebhardSBB Thanks for the bug report. 

We check, if we will programmatically disable the toggle button. As an alternative just set toggle to false (e.g. `<sbb-datepicker [toggle]="false">`) to hide the toggle if your form is in readonly mode.

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : any forecast when this issue will be fixed? thx4feedback, Florian

**Comment by FlorianGebhardSBB** [comment]
sorry, didn't want to close the issue, clicked the wrong button... :-(

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : sorry for the wrongfully closure of the issue. pls check the status after reopen... i'm not sure all the tags were correct restored after reopen?

**Comment by kyubisation** [comment]
Hello @FlorianGebhardSBB 
Our estimation is january. Depending on priority/incidents it might be delayed.

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : Kannst du schon sagen, in welches Release diese Korrektur einfliessen wird und per wann diese Release unserem Entwicklungsteam zur Verfügung stehen wird? Danke, Florian

**Comment by jeripeierSBB** [comment]
@FlorianGebhardSBB Nach jetzigem Stand mit dem nächsten Release Ende diese Woche oder anfangs nächste Woche.

**Comment by FlorianGebhardSBB** [comment]
Wie kann man über das Release informiert bleiben? Gibt es Release Notes oder einen "Newsletter" o.ä.?

**Comment by jeripeierSBB** [comment]
In Github oben rechts auf "Watch" klicken, dann "Custom" und dann "Release" anhaken. Somit bekommst du jeweils ein Mail bei jedem Release, das den Changelog gleich beinhaltet.
