### ISSUE TITLE
Bug: Select (Dropdown) widget - wrong behaviour in read-only state

### ISSUE THREAD

**Issue by FlorianGebhardSBB** [sbb-design-systems/sbb-angular#917]
**Describe the bug**
Select (Dropdown) widget behaves wrongly when in read-only state.
Compare specification with screenshot below.
Spec = https://digital.sbb.ch/en/webapps/components/select

**Expected behavior**
![image](https://user-images.githubusercontent.com/94061189/141134333-d4124b7f-7b23-49d6-8d99-6353b870b08c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/94061189/141134418-7caa3c36-ed97-47d0-803f-88bd2d84a064.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Dropdown-Felder (Select Menu)
•	werden noch mit Rahmen angezeigt
•	werden noch mit grauer Füllung (Hintergrund) angezeigt
•	Dropdown-Pfeil am rechten Feld-Ende wird noch angezeigt, kann aber nicht gedrückt/geöffnet werden

Antwort von Franco Ehrat:
•	Dropdown / Select: das gleiche wie beim Date Widget. Die UX Spezifikation ist auch hier noch nicht eingehalten. --> Bug

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : any forecast when this issue will be fixed? thx4feedback, Florian

**Comment by kyubisation** [comment]
Hello @FlorianGebhardSBB 
Our estimation is january. Depending on priority/incidents it might be delayed.

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : Kannst du schon sagen, in welches Release diese Korrektur einfliessen wird und per wann diese Release unserem Entwicklungsteam zur Verfügung stehen wird? Danke, Florian

**Comment by jeripeierSBB** [comment]
@FlorianGebhardSBB Nach jetzigem Stand mit dem nächsten Release Ende diese Woche oder anfangs nächste Woche.

**Comment by jeripeierSBB** [comment]
@FlorianGebhardSBB Nach jetzigem Stand mit dem nächsten Release Ende diese Woche oder anfangs nächste Woche.
