### ISSUE TITLE
Bug: Placeholder-texts - wrong behaviour in read-only state

### ISSUE THREAD

**Issue by FlorianGebhardSBB** [sbb-design-systems/sbb-angular#918]
**Describe the bug**
Placeholder-texts of various UI elements are still shown when in read-only state. 

**Expected behavior**
Placeholder-texts shall not be displayed. Rather showing a single "-" as recommended by Franco Ehrat (see below, additional context).
![image](https://user-images.githubusercontent.com/94061189/141136244-9c45ab2e-cf14-4a4d-9763-33dfaa28d46f.png)

**Screenshots**
Bug state: 
![image](https://user-images.githubusercontent.com/94061189/141135842-65b5e173-7ae8-44c1-982a-db0979aab9e0.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and others

**Additional context**
Problembeschreibung, die ich an Franco Ehrat gesandt habe:
Placeholder-Texte 
•	Placeholder-Texte werden angezeigt
•	macht keinen Sinn, sollten in allen Text-Widgets im «read-only» Status unterdrückt werden

Antwort von Franco Ehrat:
•	Placeholder: da bin ich auch bei dir. Das hatte ich mir bisher gar nicht überlegt. Ich würde vorschlagen, dass man in diesem Fall nicht einfach gar nichts anzeigt, sondern vielleicht einen Bindestrich.

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : any forecast when this issue will be fixed? thx4feedback, Florian

**Comment by kyubisation** [comment]
Hello @FlorianGebhardSBB 
Our estimation is january. Depending on priority/incidents it might be delayed.

**Comment by FlorianGebhardSBB** [comment]
@jeripeierSBB : Kannst du schon sagen, in welches Release diese Korrektur einfliessen wird und per wann diese Release unserem Entwicklungsteam zur Verfügung stehen wird? Danke, Florian

**Comment by jeripeierSBB** [comment]
@FlorianGebhardSBB Nach jetzigem Stand mit dem nächsten Release Ende diese Woche oder anfangs nächste Woche.
