### ISSUE TITLE
Bug: SbbNativeDateAdapter parses Date object with wrong time

### ISSUE THREAD

**Issue by k-genov** [sbb-design-systems/sbb-angular#969]
**Describe the bug**
When using the SBB_BUSINESS_DATE_ADAPTER (https://angular.app.sbb.ch/core/components/datetime) with a datepicker in an input field, the parsed date has time 00:00:00 and the **local time zone** e.g. GMT+0100 (Central European Standard Time). When converting to ISO format or UTC date, the day is suddenly wrong (one less than expected). This seems to be problem of the JS Date() constructor:
https://github.com/sbb-design-systems/sbb-angular/blob/master/src/angular/core/datetime/native-date-adapter.ts#L233 
![image](https://user-images.githubusercontent.com/62137624/145038276-fcc9b9f9-f626-4d73-8f01-666c47bcd7ae.png)

**To Reproduce**
https://stackblitz.com/edit/angular-fn7vmr?file=src/app/datepicker-business-date-adapter-example.html
![image](https://user-images.githubusercontent.com/62137624/145040108-fce419d1-e35b-436b-a1a9-17f6cd9d6fb7.png)

**Expected behaviour**
The returned date that should always have 00:00:00 UTC

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version 12

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by kyubisation** [comment]
To clarify; This is not a bug. This is how Dates in JavaScript work/are specified.
This will probably improve with the Temporal proposal, however we don't habe a timeline for that yet. (https://github.com/tc39/proposal-temporal)
I'll check what options we have here (custom date parser, timezone configuration, ...).

**Comment by kyubisation** [comment]
So, I've analyzed this a bit further and it is fairly complicated.
Basically there are three sources that dates can come from: 
- FormControl (either a Date, an ISO String or a Unix timestamp)
- User enters a string
- User select a date from the datepicker or buttons
Entering a Date in the FormControl is the only one that does not create a new Date instance, but only until it is changed by the user.
We could create dates as UTC dates, but this seems counterintuitive, as Date instances use the current timezone by default and the expectation might be broken.

My recommendation would be to use a date formatter/utility (e.g. date-fns: https://stackblitz.com/edit/js-axfk9b?file=index.js)

@k-genov What is your opinion on this?

**Comment by k-genov** [comment]
It is important that the datepicker and date adapter create the Date in the same timezone. This works correctly, both use the local timezone.

This seems to be also the specified behaviour:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date

> Note: Parsing of date strings with the Date constructor (and Date.parse(), which works the same way) is **strongly discouraged** due to browser differences and inconsistencies.
> Support for [RFC 2822](https://datatracker.ietf.org/doc/html/rfc2822) format strings is by convention only.
> Support for ISO 8601 formats differs in that date-only strings (e.g. "1970-01-01") are **treated as UTC, not local.**

I guess this just how javascript deals with dates and one should just accept it...

So from this perspective the sbb angular library should create the Date objects in the local timezone and client applications should convert the timezone as suggested, if needed. This is also the solution/workaround we have implemented.

@kyubisation I will close the issue, since the behaviour is by design correct.

**Comment by kyubisation** [comment]
Adding documentation in #1119
